/**
 * Next.js Instrumentation — runs once when the server starts.
 *
 * Validates all required environment variables upfront so missing config
 * is caught immediately instead of failing per-route at runtime.
 *
 * In local-mode (Electron launcher), CSRF_SECRET and NEXTAUTH_SECRET are
 * generated by the launcher and passed via env vars. In cloud deploys,
 * they must be set manually in the hosting provider's env config.
 */
export async function register() {
  // Only validate on the server (not during edge middleware or client build)
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    const { DashboardEnvSchema } = await import('@somnibot/shared');

    const result = DashboardEnvSchema.safeParse(process.env);

    if (!result.success) {
      const issues = result.error.issues
        .map((i) => `  ✗ ${i.path.join('.')}: ${i.message}`)
        .join('\n');

      console.error(
        '\n╔══════════════════════════════════════════════════════════╗\n' +
        '║  Dashboard Environment Validation Failed                ║\n' +
        '╚══════════════════════════════════════════════════════════╝\n' +
        '\nThe following environment variables are missing or invalid:\n\n' +
        issues +
        '\n\nSee .env.example for required values.\n' +
        'For local mode (Electron launcher), these are set automatically.\n' +
        'For cloud deploy, set them in your Railway/Vercel environment.\n',
      );

      // Don't hard-exit in local mode — the launcher sets SESSION_TOKEN
      // and CSRF is exempt, so missing CSRF_SECRET is non-fatal.
      if (!process.env.SESSION_TOKEN) {
        console.error('Aborting: cloud deploy requires all env vars. Fix the above and restart.\n');
        process.exit(1);
      } else {
        console.warn('⚠ Running in local mode — some missing env vars are non-fatal.\n');
      }
    } else {
      console.log('✓ Dashboard environment validation passed.');
    }
  }
}
