/**
 * Next.js Instrumentation — runs once when the server starts.
 *
 * Validates all required environment variables upfront so missing config
 * is caught immediately instead of failing per-route at runtime.
 *
 * In local-mode (Electron launcher), CSRF_SECRET and NEXTAUTH_SECRET are
 * generated by the launcher and passed via env vars. In cloud deploys,
 * they must be set manually in the hosting provider's env config.
 */
export async function register() {
  // Only validate on the server (not during edge middleware or client build)
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    // V10 Audit §12: Read SESSION_TOKEN from a temp file instead of env.
    // The launcher writes the token to a file with 0600 perms and passes
    // the path via SESSION_TOKEN_FILE. This avoids exposing the token in
    // /proc/<pid>/environ on Linux.
    if (process.env.SESSION_TOKEN_FILE && !process.env.SESSION_TOKEN) {
      try {
        const { readFileSync, unlinkSync } = await import('node:fs');
        const token = readFileSync(process.env.SESSION_TOKEN_FILE, 'utf-8').trim();
        if (token) {
          process.env.SESSION_TOKEN = token;
        }
        // Delete the file after reading — single-use
        try { unlinkSync(process.env.SESSION_TOKEN_FILE); } catch { /* may already be gone */ }
      } catch {
        console.warn('⚠ SESSION_TOKEN_FILE set but could not be read.');
      }
    }

    const { DashboardEnvSchema } = await import('@somnibot/shared');

    const result = DashboardEnvSchema.safeParse(process.env);

    if (!result.success) {
      process.env.DASHBOARD_ENV_VALID = 'false';
      const issues = result.error.issues
        .map((i) => `  ✗ ${i.path.join('.')}: ${i.message}`)
        .join('\n');

      console.error(
        '\n╔══════════════════════════════════════════════════════════╗\n' +
        '║  Dashboard Environment Validation Failed                ║\n' +
        '╚══════════════════════════════════════════════════════════╝\n' +
        '\nThe following environment variables are missing or invalid:\n\n' +
        issues +
        '\n\nSee .env.example for required values.\n' +
        'For local mode (Electron launcher), these are set automatically.\n' +
        'For cloud deploy, set them in your Railway/Vercel environment.\n',
      );

      // Don't hard-exit in launcher local mode. SESSION_TOKEN alone is not
      // enough to prove local mode, because a cloud deploy could accidentally
      // configure that secret and otherwise hide invalid environment config.
      const isLauncherLocalMode = process.env.SOMNIBOT_DASHBOARD_LOCAL_MODE === '1'
        || Boolean(process.env.SESSION_TOKEN_FILE && process.env.SESSION_TOKEN);

      // In launcher local mode, CSRF is exempt, so missing CSRF_SECRET is
      // non-fatal.
      //
      // Also don't hard-exit in Vercel/serverless. `process.exit(1)` turns
      // every dynamic route, including /api/health and /api/setup, into an
      // opaque platform 500 before the route can return actionable JSON.
      if (!isLauncherLocalMode && process.env.VERCEL !== '1') {
        console.error('Aborting: cloud deploy requires all env vars. Fix the above and restart.\n');
        process.exit(1);
      } else if (process.env.VERCEL === '1') {
        console.warn('⚠ Serverless runtime will continue so health/setup routes can report degraded config.\n');
      } else {
        console.warn('⚠ Running in local mode — some missing env vars are non-fatal.\n');
      }
    } else {
      process.env.DASHBOARD_ENV_VALID = 'true';
      console.log('✓ Dashboard environment validation passed.');
    }
  }
}
