import { buildFeatureManifest } from '../build-manifest.js';

const infrastructure = buildFeatureManifest;

export const INFRASTRUCTURE_MANIFESTS = [
  infrastructure({ id: 'identity-sessions', name: 'Identity and Sessions', domain: 'infrastructure', summary: 'Secure owner, staff, and customer authentication with guild-scoped authorization.', users: ['owner', 'administrator', 'moderator', 'finance', 'support', 'customer'], surfaces: { dashboardRoutes: ['/login'] }, journey: 'A legitimate user signs in once, retains a valid session across authorized surfaces, and is denied every unowned account.', invalidState: 'A credential is inaccurate, session is expired, OAuth identity is unverified, or guild and customer scope conflict.', discordBehavior: 'Discord identity is accepted only through verified OAuth or an explicit secure linking flow.', dashboardBehavior: 'Login accepts true configured credentials, preserves secure sessions, and explains recoverable authentication failures.', syntheticEvidence: 'Session fixtures prove fixation defense, expiry, refresh, CSRF, logout, role changes, cross-guild, and cross-customer denial.', liveEvidence: 'Owner, staff, and customer accounts sign in and are constrained to their real scopes after refresh and relaunch.', crossFeature: 'Team access, dashboard, portal, OAuth, SDK receipts, audit, and credential management depend on session identity.', tables: ['dashboard_user_roles', 'portal_sessions'], services: ['Supabase authentication', 'dashboard session authorization'] }),
  infrastructure({ id: 'dashboard-control-center', name: 'Dashboard Control Center', domain: 'infrastructure', summary: 'Role-specific attention, guild selection, feature state, operations, commerce, staff work, and navigation.', users: ['owner', 'administrator', 'moderator', 'finance', 'support'], surfaces: { dashboardRoutes: ['/dashboard'] }, journey: 'A signed-in operator selects a guild, sees role-relevant attention, and navigates directly to supported action and evidence.', invalidState: 'Attention is stale, unauthorized, cross-guild, duplicated, or cannot explain its required action.', discordBehavior: 'Dashboard state reflects real Discord readiness and live readback rather than optimistic configuration alone.', dashboardBehavior: 'Attention, feature state, operations, commerce exceptions, staff work, changes, actions, search, guild, and deployment state are coherent.', syntheticEvidence: 'Role and guild fixtures prove prioritization, authorization, empty, degraded, stale, and multi-guild states.', liveEvidence: 'Each staff role sees correct live attention and navigates to one resolvable action in the deployed dashboard.', crossFeature: 'Every manifest publishes state, health, attention, actions, evidence, search metadata, and authorization to the dashboard.' }),
  infrastructure({ id: 'installation-deployment-recovery', name: 'Installation, Deployment, and Recovery', domain: 'infrastructure', summary: 'Launcher-owned credentials, services, updates, backup, migration, health, and recovery.', users: ['owner', 'administrator', 'support'], surfaces: { dashboardRoutes: ['/setup'], scenarioProofs: ['infrastructure-launcher'] }, journey: 'An owner installs one isolated runtime, verifies exact state, upgrades through compatibility gates, and can recover it.', invalidState: 'Credentials, versions, migration head, backup freshness, resources, provider health, or runtime ownership are unsafe.', discordBehavior: 'Only the elected runtime connects; shutdown drains work before another instance acquires ownership.', dashboardBehavior: 'Setup and deployment status expose exact SHA, lifecycle, migration, providers, queues, backup, recovery, and guidance.', syntheticEvidence: 'Process fixtures prove first boot, credential rotation, single-instance lease, upgrade gate, drain, crash, restore, and migration.', liveEvidence: 'One VPS Compose runtime restarts, upgrades, and restores with exact-SHA and Discord behavioral readback.', crossFeature: 'Launcher owns lifecycle; System State supplies dashboard truth; feature manifests define post-change verification.', services: ['launcher', 'runtime lease', 'dashboard supervisor', 'backup and restore'], tables: ['instance_settings', 'runtime_leases'] }),
  infrastructure({ id: 'privacy-governance', name: 'Privacy and Data Governance', domain: 'infrastructure', summary: 'Feature-specific data purpose, retention, export, erasure, anonymization, and backup policy.', users: ['owner', 'administrator', 'support', 'member', 'customer'], surfaces: { dashboardRoutes: ['/privacy'] }, journey: 'An authorized subject or owner requests export or erasure and receives a scoped, explainable, audited outcome.', invalidState: 'The request lacks identity proof, scope, retention analysis, feature ownership, or safe delivery.', discordBehavior: 'Privacy responses expose no protected data in public channels and honor feature-specific retention rules.', dashboardBehavior: 'Owners inspect policy coverage while subjects use supported export, erasure, and recovery paths.', syntheticEvidence: 'Data maps prove every manifest declares governance and export or erasure reaches all owned stores and backups.', liveEvidence: 'A test member export and erasure flow completes with retained legal records explained and anonymized.', crossFeature: 'Every feature manifest owns its data rules; audit, commerce retention, backups, analytics, portal, and incidents enforce them.' }),
] as const;

export const MUSIC_MANIFESTS = [
  infrastructure({ id: 'music-playback', name: 'Music Playback', domain: 'music', summary: 'Reliable Lavalink voice connection, collaborative queue, playback controls, and fairness.', users: ['administrator', 'member'], surfaces: { dashboardRoutes: ['/music'], botFeatures: ['music'], scenarioProofs: ['music-collaborative-queue', 'music-player-fairness'], commands: ['/play', '/pause', '/resume', '/skip', '/stop', '/queue', '/disconnect'], interactions: ['music control buttons'], events: ['voiceStateUpdate'] }, journey: 'A member queues a track, hears playback, advances the queue, stops, and disconnects without reconnect loops.', invalidState: 'No playable source, missing voice permission, stale player, wrong channel, duplicate node, or corrupt queue state.', discordBehavior: 'The bot joins once, plays audibly, keeps controls and queue synchronized, and leaves only on explicit or policy action.', dashboardBehavior: 'Node, player, queue, current track, voice state, controls, fairness, and failures reflect live state.', syntheticEvidence: 'Player fakes prove join races, empty queue, move, retry, node loss, restart, fairness, and control idempotency.', liveEvidence: 'Real Discord voice playback is audibly confirmed through play, queue advance, stop, and three disconnect cycles.', crossFeature: 'Voice permissions, temporary channels, roles, notifications, audit, operational modes, and fair scheduling interact.', services: ['Lavalink player manager', 'voice connection reconciler', 'collaborative queue'], tables: ['guild_config'], slo: { signal: 'Music control responsiveness', target: 'Controls acknowledge promptly and player state converges within the music interaction budget.', measurement: 'Measure Discord control receipt through Lavalink and voice-state readback.' } }),
] as const;
