export const FEATURE_COMMANDS: Readonly<Record<string, readonly string[]>> = {
  'member-profiles': ['/profile', '/title', '/bio'],
  levels: ['/rank', '/leaderboard', '/xp'],
  giveaways: ['/giveaway'],
  'polls-predictions': ['/poll', '/predict'],
  'temporary-channels': ['/voice'],
  'discord-experience': ['/help'],
  tutorials: ['/tutorial'],
  'economy-core': [
    '/balance', '/daily', '/weekly', '/monthly', '/work', '/crime', '/beg', '/search',
    '/deposit', '/withdraw', '/pay', '/rob', '/passive', '/shop', '/buy', '/sell',
    '/inventory', '/use', '/economy-leaderboard', '/collect-income', '/timers',
  ],
  gathering: ['/hunt', '/dig', '/mine'],
  crafting: ['/craft', '/recipes'],
  farming: ['/farm'],
  fishing: ['/fish'],
  adventures: ['/adventure'],
  market: ['/market'],
  trivia: ['/trivia'],
  heists: ['/heist'],
  'games-lottery': [
    '/coinflip', '/slots', '/rps', '/dice', '/blackjack', '/highlow', '/scratch', '/guess', '/lottery',
  ],
  pets: ['/pet'],
  quests: ['/quests'],
  achievements: ['/badges', '/prestige'],
  'moderation-actions': ['/warn', '/mute', '/kick', '/ban', '/pardon', '/infractions', '/purge'],
  appeals: ['/appeal'],
  'tickets-transcripts': ['/ticket'],
  'server-setup-sync': ['/setup'],
  'payments-fulfillment': ['/store'],
  'project-licensing': ['/license'],
  'privacy-governance': ['/forgetme', '/privacy', '/mydata'],
  'music-playback': [
    '/play', '/skip', '/stop', '/queue', '/np', '/volume', '/loop', '/shuffle', '/seek',
    '/remove', '/move', '/pause', '/filter',
  ],
} as const;
