import type { FeatureConfigurationField } from './schema.js';

type FeatureAcceptanceContract = {
  readonly configurationFields: readonly FeatureConfigurationField[];
  readonly validStates: readonly string[];
  readonly persistenceRequirements: readonly string[];
  readonly restartAndRecovery: readonly string[];
  readonly cleanupBehavior: readonly string[];
};

type FieldType = FeatureConfigurationField['valueType'];

function field(key: string, valueType: FieldType, purpose: string): FeatureConfigurationField {
  return { key, valueType, required: true, purpose };
}

function contract(featureContract: FeatureAcceptanceContract): FeatureAcceptanceContract {
  return featureContract;
}

const FEATURE_CONTRACTS: Readonly<Record<string, FeatureAcceptanceContract>> = {
  'product-store': contract({ configurationFields: [field('defaultCurrency', 'string', 'Currency used by newly-authored plans.'), field('launchGateEnabled', 'boolean', 'Require sandbox launch proof before activation.')], validStates: ['draft', 'inactive-policy-ready', 'sandbox-verified', 'active', 'retired'], persistenceRequirements: ['Products, plans, files, capability grants, and launch receipts remain revision-linked.'], restartAndRecovery: ['Interrupted launch runs resume from the last durable stage without activating the product.'], cleanupBehavior: ['Retiring a product preserves orders and entitlements while preventing new checkout.'] }),
  'payments-fulfillment': contract({ configurationFields: [field('paypalWebhookId', 'identifier', 'Webhook identity accepted for signed commerce events.'), field('fulfillmentRetryLimit', 'integer', 'Bounded delivery attempts before an exception is opened.')], validStates: ['payment-pending', 'payment-verified', 'fulfillment-pending', 'fulfilled', 'reversed'], persistenceRequirements: ['Provider event identity, order, payment, entitlement, and fulfillment attempts commit idempotently.'], restartAndRecovery: ['Replayed webhooks and restarted workers continue the same operation without duplicate entitlement.'], cleanupBehavior: ['Refund or cancellation compensation revokes only access sourced by the reversed transaction.'] }),
  'customer-operations': contract({ configurationFields: [field('identityMatchPolicy', 'string', 'Evidence required to link a payer, portal user, and Discord member.'), field('supportRetentionDays', 'duration', 'Retention window for customer support history.')], validStates: ['unlinked', 'verified-linked', 'conflict-review', 'access-recovered'], persistenceRequirements: ['Identity links and staff resolutions retain actor, guild, evidence, and operation identity.'], restartAndRecovery: ['Unfinished relinks reopen as conflicts rather than silently selecting an account.'], cleanupBehavior: ['Unlinking removes the relationship, not independently retained merchant records.'] }),
  'project-licensing': contract({ configurationFields: [field('installationLimit', 'integer', 'Maximum concurrent installations per entitlement.'), field('offlineGraceSeconds', 'duration', 'Bounded offline validation window.')], validStates: ['inactive-policy-draft', 'policy-saved', 'integration-current', 'integration-stale', 'revoked'], persistenceRequirements: ['Product policy revisions, installations, heartbeats, and license state remain product-scoped.'], restartAndRecovery: ['Restart restores installation counts and policy revision before accepting validation.'], cleanupBehavior: ['Revocation releases installations and invalidates cached access after the policy grace window.'] }),
  'somnibot-sdk': contract({ configurationFields: [field('protocolVersion', 'string', 'SomniBot licensing protocol implemented by the generated contract.'), field('conformanceProfiles', 'string-list', 'Project-native behaviors the integration must prove.')], validStates: ['contract-generated', 'implementation-unverified', 'integrated-current', 'policy-stale', 'conformance-failed'], persistenceRequirements: ['Contract hash, product revision, project commit, and conformance receipt remain linked.'], restartAndRecovery: ['A rerun for the same inputs reproduces contract identity; interrupted verification remains unverified.'], cleanupBehavior: ['Superseded receipts remain auditable but cannot establish current conformance.'] }),
  'revenue-exceptions': contract({ configurationFields: [field('severityRouting', 'object-list', 'Exception type to owner and escalation mapping.'), field('fraudHoldPolicy', 'string', 'Access behavior while suspected fraud is reviewed.')], validStates: ['open', 'owned', 'investigating', 'resolved', 'compensated'], persistenceRequirements: ['Every exception retains provider evidence, affected entitlement, owner, and resolution operation.'], restartAndRecovery: ['Unresolved exceptions return to the assigned queue after worker or dashboard restart.'], cleanupBehavior: ['Resolution closes alerts only after payment and entitlement readback agree.'] }),
  'customer-portal': contract({ configurationFields: [field('sessionLifetimeSeconds', 'duration', 'Authenticated customer portal session lifetime.'), field('downloadTokenLifetimeSeconds', 'duration', 'One-time download authorization lifetime.')], validStates: ['signed-out', 'authenticated', 'entitled', 'support-pending', 'access-revoked'], persistenceRequirements: ['Portal sessions, customer links, requests, and download grants remain customer and guild scoped.'], restartAndRecovery: ['Expired sessions require authentication while durable requests and entitlements remain available.'], cleanupBehavior: ['Logout and identity unlink revoke sessions and unused download grants.'] }),
  'merchant-analytics': contract({ configurationFields: [field('reportingTimezone', 'string', 'Timezone used for merchant period boundaries.'), field('exportColumns', 'string-list', 'Approved deterministic export columns.')], validStates: ['current', 'reconciliation-stale', 'provider-delayed', 'export-ready'], persistenceRequirements: ['Export rows retain stable identifiers while payment and entitlement states remain separate.'], restartAndRecovery: ['Interrupted exports restart from a stable cursor and produce the same ordering.'], cleanupBehavior: ['Expired generated files are removed without deleting source commerce records.'] }),
  'economy-core': contract({ configurationFields: [field('currencyDefinitions', 'object-list', 'Currencies, precision, and transfer rules.'), field('dailyGrantPolicy', 'object', 'Eligibility and amount for scheduled grants.')], validStates: ['enabled', 'paused', 'ledger-reconciling'], persistenceRequirements: ['Every balance change is represented by an idempotent guild-scoped ledger entry.'], restartAndRecovery: ['Balances rebuild from the ledger and scheduled grants resume without duplication.'], cleanupBehavior: ['Guild removal deletes spendable balances only after the configured export and retention workflow.'] }),
  'shop-items': contract({ configurationFields: [field('itemDefinitions', 'object-list', 'Purchasable items and executable effects.'), field('purchaseLimits', 'object', 'Per-member and per-period purchase limits.')], validStates: ['draft-item', 'active-item', 'sold-out', 'retired-item'], persistenceRequirements: ['Catalog revisions, inventory, purchases, and effect receipts remain linked.'], restartAndRecovery: ['Pending effects retry from the purchase receipt without charging again.'], cleanupBehavior: ['Retired items stop new purchases while owned durable items retain defined behavior.'] }),
  'gathering': contract({ configurationFields: [field('resourcePools', 'object-list', 'Gatherable resources, weights, and requirements.'), field('gatherCooldownSeconds', 'duration', 'Per-member gathering cooldown.')], validStates: ['ready', 'cooldown', 'resource-exhausted', 'paused'], persistenceRequirements: ['Gather rolls and grants share one idempotent economy operation.'], restartAndRecovery: ['Cooldowns and pending grants survive restart using durable timestamps and operation IDs.'], cleanupBehavior: ['Removing a pool blocks new rolls without deleting already-owned resources.'] }),
  'crafting': contract({ configurationFields: [field('recipeDefinitions', 'object-list', 'Ingredients, outputs, requirements, and executable effects.'), field('craftingQueueLimit', 'integer', 'Maximum concurrent queued crafts per member.')], validStates: ['recipe-draft', 'recipe-active', 'craft-pending', 'craft-complete'], persistenceRequirements: ['Ingredient consumption and output grant commit atomically against the recipe revision.'], restartAndRecovery: ['Interrupted crafts resume or compensate consumed inputs exactly once.'], cleanupBehavior: ['Retired recipes stop new crafts while completed outputs remain valid.'] }),
  'farming': contract({ configurationFields: [field('cropDefinitions', 'object-list', 'Growth stages, yields, and item relationships.'), field('plotLimit', 'integer', 'Maximum plots available to a member.')], validStates: ['empty-plot', 'growing', 'ready-to-harvest', 'withered'], persistenceRequirements: ['Plant time, crop revision, plot state, and harvested grants remain durable.'], restartAndRecovery: ['Elapsed growth is recalculated from persisted timestamps after downtime.'], cleanupBehavior: ['Plot reset compensates only unharvested state and never duplicates yield.'] }),
  'fishing': contract({ configurationFields: [field('fishingTables', 'object-list', 'Catch tables, rarity, location, and requirements.'), field('fishingCooldownSeconds', 'duration', 'Per-member fishing cooldown.')], validStates: ['ready', 'cast-pending', 'caught', 'cooldown'], persistenceRequirements: ['Catch outcome, inventory grant, tool effect, and operation identity remain linked.'], restartAndRecovery: ['Restart resolves pending casts without rerolling or double-granting a catch.'], cleanupBehavior: ['Removing a table prevents future casts while preserving caught items.'] }),
  'adventures': contract({ configurationFields: [field('adventureDefinitions', 'object-list', 'Stages, choices, risks, rewards, and requirements.'), field('activeAdventureLimit', 'integer', 'Concurrent adventures allowed per member.')], validStates: ['available', 'in-progress', 'completed', 'failed', 'expired'], persistenceRequirements: ['Adventure revision, member choices, stage state, and rewards remain durable.'], restartAndRecovery: ['A restart resumes the current stage without rerolling resolved choices.'], cleanupBehavior: ['Cancellation follows the adventure compensation rule and cannot duplicate rewards.'] }),
  'market': contract({ configurationFields: [field('listingRules', 'object', 'Eligible items, price bounds, fees, and expiry.'), field('listingLimit', 'integer', 'Concurrent listings permitted per member.')], validStates: ['listed', 'reserved', 'sold', 'expired', 'cancelled'], persistenceRequirements: ['Escrow, listing, purchase ledger entries, and ownership transfer commit atomically.'], restartAndRecovery: ['Reserved purchases recover to sold or listed without losing currency or items.'], cleanupBehavior: ['Cancellation and expiry release escrow exactly once.'] }),
  'trivia': contract({ configurationFields: [field('questionProviders', 'object-list', 'Configured question sources and category mappings.'), field('roundPolicy', 'object', 'Round count, timing, scoring, and repeat avoidance.')], validStates: ['idle', 'round-open', 'answer-locked', 'complete'], persistenceRequirements: ['Round identity, served question hashes, answers, and scores survive within the session.'], restartAndRecovery: ['Restart closes or resumes a round according to its persisted deadline without repeating questions.'], cleanupBehavior: ['Session cleanup removes transient questions while preserving awarded ledger entries.'] }),
  'heists': contract({ configurationFields: [field('heistDefinitions', 'object-list', 'Lobby, roles, stages, odds, and reward rules.'), field('lobbyTimeoutSeconds', 'duration', 'Time allowed for a multiplayer lobby to form.')], validStates: ['lobby-open', 'running', 'resolved-success', 'resolved-failure', 'cancelled'], persistenceRequirements: ['Participants, stakes, stage outcomes, and payouts share one heist operation.'], restartAndRecovery: ['Restart resumes an unresolved stage from persisted randomness and membership.'], cleanupBehavior: ['Cancelled lobbies return stakes once; resolved heists retain their result.'] }),
  'games-lottery': contract({ configurationFields: [field('gameDefinitions', 'object-list', 'Playable games, wager limits, and reward tables.'), field('drawSchedule', 'string', 'Lottery draw schedule and timezone.')], validStates: ['game-open', 'game-resolved', 'draw-open', 'draw-locked', 'draw-complete'], persistenceRequirements: ['Wagers, tickets, randomness commitment, result, and payout remain auditable.'], restartAndRecovery: ['Restart uses the committed draw seed and never redraws a completed outcome.'], cleanupBehavior: ['Expired games close entries and compensate only unresolved wagers.'] }),
  'pets': contract({ configurationFields: [field('petDefinitions', 'object-list', 'Species, custom emoji, growth, stats, and abilities.'), field('petActionCooldowns', 'object', 'Cooldowns for care, training, and battle actions.')], validStates: ['owned', 'resting', 'training', 'battle-ready', 'retired'], persistenceRequirements: ['Pet identity, appearance, progression, inventory, and battle state remain durable.'], restartAndRecovery: ['Restart restores action cooldowns and resolves pending battle rewards once.'], cleanupBehavior: ['Retiring a pet removes active effects while preserving history and configured ownership policy.'] }),
  'quests': contract({ configurationFields: [field('questDefinitions', 'object-list', 'Objectives, progress sources, rewards, and eligibility.'), field('activeQuestLimit', 'integer', 'Concurrent member quest limit.')], validStates: ['available', 'active', 'complete-unclaimed', 'claimed', 'expired'], persistenceRequirements: ['Objective events, progress, quest revision, and reward claim share stable identities.'], restartAndRecovery: ['Restart resumes active progress and prevents repeated reward claims.'], cleanupBehavior: ['Expired or retired quests stop progress while preserving prior claims.'] }),
  'achievements': contract({ configurationFields: [field('achievementDefinitions', 'object-list', 'Criteria, tiers, visibility, and rewards.'), field('retroactiveEvaluation', 'boolean', 'Whether eligible history may unlock new definitions.')], validStates: ['locked', 'progressing', 'unlocked', 'rewarded'], persistenceRequirements: ['Criteria revision, progress evidence, unlock, and reward receipt remain linked.'], restartAndRecovery: ['Restart replays only unprocessed evidence and cannot unlock or reward twice.'], cleanupBehavior: ['Retired achievements remain visible according to policy but stop evaluating new progress.'] }),
  'member-profiles': contract({ configurationFields: [field('profileFields', 'object-list', 'Visible profile fields and member edit policy.'), field('profileVisibility', 'string', 'Audience allowed to view member profile data.')], validStates: ['private', 'guild-visible', 'partially-redacted'], persistenceRequirements: ['Member-owned fields, visibility, and derived progression references remain guild scoped.'], restartAndRecovery: ['Profile reads recover from durable member state after cache loss.'], cleanupBehavior: ['Member erasure removes or anonymizes profile fields without corrupting shared rankings.'] }),
  'welcome-onboarding': contract({ configurationFields: [field('onboardingSteps', 'object-list', 'Ordered Discord onboarding and SomniBot guidance steps.'), field('welcomeDestination', 'identifier', 'Channel or direct-message destination for welcome output.')], validStates: ['not-started', 'in-progress', 'completed', 'dismissed', 'blocked'], persistenceRequirements: ['Member progress and granted onboarding roles persist per guild and step revision.'], restartAndRecovery: ['Restart resumes incomplete members at the first unmet prerequisite.'], cleanupBehavior: ['Member departure cancels pending actions and applies configured onboarding-role cleanup.'] }),
  'branding': contract({ configurationFields: [field('logoAsset', 'identifier', 'Stored logo asset used by supported surfaces.'), field('themeTokens', 'object', 'Color, typography, background, and header presentation tokens.')], validStates: ['default', 'draft', 'published', 'asset-degraded'], persistenceRequirements: ['Validated asset references and published theme revision remain guild scoped.'], restartAndRecovery: ['Unavailable assets fall back safely while retaining the selected theme revision.'], cleanupBehavior: ['Replacing an asset releases the prior stored object only when no published revision references it.'] }),
  'levels': contract({ configurationFields: [field('xpRules', 'object-list', 'XP sources, cooldowns, exclusions, and multipliers.'), field('levelRewards', 'object-list', 'Role, currency, item, and effect rewards by level.')], validStates: ['eligible', 'cooldown', 'level-up-pending', 'rewarded'], persistenceRequirements: ['XP ledger, computed level, reward revision, and reward receipts remain consistent.'], restartAndRecovery: ['Restart recomputes from durable XP and retries only unfulfilled rewards.'], cleanupBehavior: ['Reward rule removal never retracts prior grants unless an explicit reversible removal effect exists.'] }),
  'reaction-roles': contract({ configurationFields: [field('rolePanels', 'object-list', 'Messages containing multiple emoji or component to role mappings.'), field('removeOnUnreact', 'boolean', 'Whether removal of a reaction removes its mapped role.')], validStates: ['panel-draft', 'panel-active', 'mapping-disabled', 'message-missing'], persistenceRequirements: ['Message, interaction key, role, mode, and assignment receipt remain linked.'], restartAndRecovery: ['Restart rehydrates active panels and reconciles stale messages or roles before handling events.'], cleanupBehavior: ['Panel deletion removes listeners and optionally compensates panel-owned role assignments.'] }),
  'giveaways': contract({ configurationFields: [field('giveawayRules', 'object', 'Eligibility, entry mode, winner count, and reroll policy.'), field('giveawayDurationSeconds', 'duration', 'Default giveaway entry duration.')], validStates: ['draft', 'open', 'locked', 'drawn', 'cancelled'], persistenceRequirements: ['Entries, eligibility snapshot, randomness commitment, winners, and rerolls remain durable.'], restartAndRecovery: ['Restart reconstructs timers and never redraws a committed result.'], cleanupBehavior: ['Cancellation closes entry and applies the declared prize compensation.'] }),
  'scheduled-messages': contract({ configurationFields: [field('schedules', 'object-list', 'Destinations, content, timezone, recurrence, and limits.'), field('misfirePolicy', 'string', 'Behavior for occurrences missed during downtime.')], validStates: ['draft', 'scheduled', 'dispatching', 'paused', 'completed'], persistenceRequirements: ['Schedule revision, next occurrence, dispatch identity, and result remain durable.'], restartAndRecovery: ['Restart applies the configured misfire policy without duplicate sends.'], cleanupBehavior: ['Deletion cancels future occurrences while preserving dispatch audit history.'] }),
  'polls-predictions': contract({ configurationFields: [field('pollDefinitions', 'object-list', 'Options, eligibility, close time, and visibility.'), field('predictionSettlementPolicy', 'string', 'Who may settle and how rewards are calculated.')], validStates: ['draft', 'open', 'locked', 'settled', 'cancelled'], persistenceRequirements: ['Votes or stakes, close state, result, and settlement receipts remain durable.'], restartAndRecovery: ['Restart restores deadlines and cannot accept after lock or settle twice.'], cleanupBehavior: ['Cancellation follows the configured anonymity and stake-return behavior.'] }),
  'temporary-channels': contract({ configurationFields: [field('voiceTemplates', 'object-list', 'Category, naming, permissions, ownership, and limits.'), field('emptyDeleteDelaySeconds', 'duration', 'Delay before deleting an empty temporary channel.')], validStates: ['template-active', 'channel-occupied', 'channel-empty-pending-delete', 'channel-deleted'], persistenceRequirements: ['Created channel identity, owner, template revision, and cleanup deadline remain durable.'], restartAndRecovery: ['Restart reconciles live channels before rescheduling empty cleanup.'], cleanupBehavior: ['Cleanup deletes only template-owned empty channels and clears their references.'] }),
  'statistics-channels': contract({ configurationFields: [field('counterDefinitions', 'object-list', 'Statistic source, channel, format, and refresh policy.'), field('refreshIntervalSeconds', 'duration', 'Minimum refresh interval for counter updates.')], validStates: ['current', 'refresh-pending', 'permission-blocked', 'source-degraded'], persistenceRequirements: ['Last applied value, source revision, and next refresh remain guild scoped.'], restartAndRecovery: ['Restart recomputes from authoritative sources and coalesces missed refreshes.'], cleanupBehavior: ['Removing a counter stops updates without deleting a shared channel unless it is explicitly owned.'] }),
  'discord-experience': contract({ configurationFields: [field('embedTemplates', 'object-list', 'Reusable embed content, assets, and mention policy.'), field('componentPolicies', 'object', 'Allowed interactive components and authorization rules.')], validStates: ['draft', 'validated', 'published', 'asset-degraded'], persistenceRequirements: ['Template revisions and published message references remain guild scoped.'], restartAndRecovery: ['Restart restores registered component handlers before accepting interactions.'], cleanupBehavior: ['Retiring a template disables owned interactions while preserving sent-message history.'] }),
  'tutorials': contract({ configurationFields: [field('guidanceTracks', 'object-list', 'Audience, steps, prerequisites, and completion behavior.'), field('tutorialVisibility', 'string', 'Owner-controlled enabled, hidden, or disabled guidance state.')], validStates: ['available', 'in-progress', 'completed', 'hidden', 'disabled'], persistenceRequirements: ['Per-user progress and owner visibility policy remain separate and durable.'], restartAndRecovery: ['Restart resumes at the first incomplete step without forcing hidden guidance open.'], cleanupBehavior: ['Reset clears only selected progress; disabling stops prompts without deleting configuration.'] }),
  'starboard': contract({ configurationFields: [field('boardDefinitions', 'object-list', 'Source scope, emoji, threshold, destination, and exclusions.'), field('selfReactionPolicy', 'string', 'Whether author reactions count toward threshold.')], validStates: ['tracking', 'qualified', 'posted', 'below-threshold', 'source-missing'], persistenceRequirements: ['Source message, qualifying reactors, board message, and board revision remain linked.'], restartAndRecovery: ['Restart reconciles reactions and existing board posts without duplication.'], cleanupBehavior: ['Source deletion removes or tombstones the board post according to configured policy.'] }),
  'moderation-actions': contract({ configurationFields: [field('infractionPolicy', 'object', 'Action reasons, durations, escalation, and pardon rules.'), field('moderationEvidenceRetentionDays', 'duration', 'Retention window for infraction evidence.')], validStates: ['previewed', 'committed', 'discord-confirmed', 'reversed'], persistenceRequirements: ['Infraction, Discord effect, actor, target, reason, and operation identity remain linked.'], restartAndRecovery: ['Restart reconciles committed actions lacking Discord or audit readback.'], cleanupBehavior: ['Pardon or reversal compensates only effects owned by the original infraction.'] }),
  'automod-anti-raid': contract({ configurationFields: [field('orderedRules', 'object-list', 'Ordered matchers, exemptions, thresholds, and actions.'), field('raidWindowSeconds', 'duration', 'Window used to evaluate coordinated join activity.')], validStates: ['draft', 'simulation-clean', 'active', 'degraded-permission', 'paused'], persistenceRequirements: ['Rule revision, matched event, exemption decision, and enforcement operation remain auditable.'], restartAndRecovery: ['Restart restores rate windows conservatively and suppresses replayed event punishment.'], cleanupBehavior: ['Rule retirement stops evaluation and cancels only pending actions sourced by that rule.'] }),
  'appeals': contract({ configurationFields: [field('appealEligibility', 'object', 'Eligible infractions, windows, forms, and conflict policy.'), field('appealDestination', 'identifier', 'Staff destination for appeal review.')], validStates: ['eligible', 'submitted', 'under-review', 'approved', 'denied', 'closed'], persistenceRequirements: ['Appeal, infraction, evidence, reviewer, decision, remedy, and notification remain linked.'], restartAndRecovery: ['Restart returns undecided appeals to the review queue without changing eligibility.'], cleanupBehavior: ['Erasure redacts member-authored content while retaining required moderation decision evidence.'] }),
  'tickets-transcripts': contract({ configurationFields: [field('panelDefinitions', 'object-list', 'Panels, forms, categories, routing, limits, and permissions.'), field('transcriptRetentionDays', 'duration', 'Retention window for redacted ticket transcripts.')], validStates: ['panel-active', 'ticket-open', 'ticket-pending-close', 'ticket-closed', 'ticket-reopened'], persistenceRequirements: ['Panel revision, ticket channel, participants, lifecycle, and transcript authorization remain linked.'], restartAndRecovery: ['Restart reconciles open ticket channels and resumes incomplete close or transcript work.'], cleanupBehavior: ['Deletion removes the private channel and transcript only after retention and export rules permit.'] }),
  'message-logging': contract({ configurationFields: [field('loggedEventTypes', 'string-list', 'Discord message events eligible for logging.'), field('excludedChannels', 'string-list', 'Channels whose message content must never be retained.')], validStates: ['enabled', 'redacting', 'retention-purge', 'destination-degraded'], persistenceRequirements: ['Eligible event metadata and allowed redacted content persist only for the configured retention window.'], restartAndRecovery: ['Partial Discord events are marked incomplete and retention work resumes after restart.'], cleanupBehavior: ['Retention and erasure remove content while preserving non-personal integrity evidence where required.'] }),
  'role-channel-management': contract({ configurationFields: [field('roleTierRules', 'object-list', 'Hierarchy inference, manual tiers, and assignment boundaries.'), field('managedChannelDefinitions', 'object-list', 'Intended channels, permission overwrites, and ownership.')], validStates: ['imported', 'draft-diff', 'validated', 'applied', 'drifted'], persistenceRequirements: ['Intended configuration, live identity mapping, release, and readback remain linked.'], restartAndRecovery: ['Restart resumes an interrupted release from durable operation stages and fresh Discord facts.'], cleanupBehavior: ['Rollback reverses owned changes in dependency order and preserves unrelated guild structure.'] }),
  'server-setup-sync': contract({ configurationFields: [field('adoptionTracks', 'string-list', 'Owner-selected feature tracks to deploy.'), field('sourceGuildId', 'identifier', 'Read-only guild used for dashboard-and-bot assisted copying.')], validStates: ['source-loaded', 'target-selected', 'preview-valid', 'deploying', 'verified', 'partially-failed'], persistenceRequirements: ['Source snapshot, target plan, created identities, operation stages, and readback remain durable.'], restartAndRecovery: ['Restart resumes only unfinished target operations after revalidating source read-only status.'], cleanupBehavior: ['Compensation removes target-owned test artifacts and never mutates the source guild.'] }),
  'team-access': contract({ configurationFields: [field('staffRoleScopes', 'object-list', 'Dashboard and Discord permissions granted by each staff role.'), field('invitationLifetimeSeconds', 'duration', 'Single-use staff invitation validity window.')], validStates: ['invited', 'active', 'scope-changed', 'revoked', 'expired'], persistenceRequirements: ['Invitation token hash, acceptance, role scope, sessions, and revocation remain guild scoped.'], restartAndRecovery: ['Restart preserves revocation and expires outstanding sessions before accepting further actions.'], cleanupBehavior: ['Removing staff revokes sessions and invitations without deleting attributed audit history.'] }),
  'automations': contract({ configurationFields: [field('automationGraphs', 'object-list', 'Typed triggers, conditions, actions, and failure policy.'), field('maxExecutionDepth', 'integer', 'Hard recursion depth for chained automation execution.')], validStates: ['draft', 'simulation-valid', 'active', 'paused', 'dependency-blocked'], persistenceRequirements: ['Graph revision, trigger identity, execution path, action receipts, and cooldowns remain durable.'], restartAndRecovery: ['Restart resumes retryable actions without re-entering the same event graph.'], cleanupBehavior: ['Disabling a graph cancels queued graph-owned work while preserving execution history.'] }),
  'webhook-relays': contract({ configurationFields: [field('relayDefinitions', 'object-list', 'Signature scheme, input schema, transform, and destination.'), field('replayWindowSeconds', 'duration', 'Maximum signed-request age and nonce retention window.')], validStates: ['provisioned', 'active', 'rotation-overlap', 'rate-limited', 'disabled'], persistenceRequirements: ['Relay identity, secret version metadata, nonce, request hash, and delivery receipt remain durable.'], restartAndRecovery: ['Restart retains replay protection and retries only undelivered accepted events.'], cleanupBehavior: ['Deletion revokes active secret versions and expires retained nonces after the replay window.'] }),
  'custom-commands': contract({ configurationFields: [field('commandDefinitions', 'object-list', 'Names, typed options, permissions, responses, and effects.'), field('commandCooldowns', 'object', 'Per-command and per-member cooldown policy.')], validStates: ['draft', 'validated', 'active', 'collision-blocked', 'disabled'], persistenceRequirements: ['Command revision, invocation, effect operation, and cooldown remain guild scoped.'], restartAndRecovery: ['Restart registers the active revision and does not replay completed effects.'], cleanupBehavior: ['Deletion unregisters the command and cancels pending command-owned effects.'] }),
  'operation-queue': contract({ configurationFields: [field('retryPolicies', 'object-list', 'Backoff, retry limit, compensation, and dead-letter behavior.'), field('workloadPriorities', 'object-list', 'Fair scheduling priorities by feature workload.')], validStates: ['draft', 'validated', 'committed', 'executing', 'readback-complete', 'failed', 'compensated'], persistenceRequirements: ['Operation, actor, source, mutation, queue attempts, effects, readback, and audit share one identity.'], restartAndRecovery: ['Restart leases unfinished work safely and recovers expired leases without duplicate effects.'], cleanupBehavior: ['Terminal cleanup archives operation evidence and releases leases without hiding failures.'] }),
  'audit-history': contract({ configurationFields: [field('auditRetentionPolicies', 'object-list', 'Retention by event class and regulatory purpose.'), field('integrityCheckpointInterval', 'integer', 'Event interval for tamper-evident integrity checkpoints.')], validStates: ['accepted', 'integrity-verified', 'redacted', 'retention-locked', 'exported'], persistenceRequirements: ['Append-only events retain actor, guild, operation, safe details, ordering, and integrity links.'], restartAndRecovery: ['Restart verifies the last checkpoint before accepting new critical events.'], cleanupBehavior: ['Retention removes eligible detail while preserving required integrity and attribution metadata.'] }),
  'diagnostics-incidents': contract({ configurationFields: [field('incidentSeverityRules', 'object-list', 'Health conditions mapped to severity and responders.'), field('diagnosticBundleSections', 'string-list', 'Approved redacted sections included in diagnostics.')], validStates: ['healthy', 'degraded', 'incident-open', 'mitigating', 'recovering', 'resolved'], persistenceRequirements: ['Incident timeline, affected features, operations, mitigation, and recovery evidence remain durable.'], restartAndRecovery: ['Restart restores open incidents and waits for live recovery evidence before resolution.'], cleanupBehavior: ['Diagnostic bundles expire independently while incident and audit records follow retention policy.'] }),
  'system-settings': contract({ configurationFields: [field('providerSettings', 'object-list', 'Masked provider configuration and validation status.'), field('notificationPolicy', 'object', 'Severity, audience, delivery, quiet hours, and escalation.')], validStates: ['draft', 'validated', 'active', 'dependency-blocked', 'rollback-ready'], persistenceRequirements: ['Activated settings are versioned with actor, source, impact preview, and runtime readback.'], restartAndRecovery: ['Restart loads only the last validated active generation and reports reload failures.'], cleanupBehavior: ['Replacing credentials revokes prior versions without exposing secret material in settings history.'] }),
  'identity-sessions': contract({ configurationFields: [field('sessionLifetimeSeconds', 'duration', 'Authenticated dashboard session lifetime.'), field('reauthenticationActions', 'string-list', 'Sensitive operations that require recent authentication.')], validStates: ['anonymous', 'authenticated', 'reauth-required', 'revoked', 'expired'], persistenceRequirements: ['OAuth identity, guild authorization, session metadata, and revocation remain scoped and auditable.'], restartAndRecovery: ['Restart preserves session validity and revocation from the authoritative store.'], cleanupBehavior: ['Logout, staff revocation, and identity unlink invalidate affected sessions immediately.'] }),
  'dashboard-control-center': contract({ configurationFields: [field('attentionViewRules', 'object-list', 'Role-specific work prioritization and visibility.'), field('globalSearchSources', 'string-list', 'Authorized domains indexed for dashboard discovery.')], validStates: ['ready', 'partial-data', 'provider-degraded', 'read-only'], persistenceRequirements: ['Selected guild, role view, attention state, and deployment facts come from authoritative services.'], restartAndRecovery: ['Restart rebuilds derived attention and search indexes without losing underlying operations.'], cleanupBehavior: ['Cache cleanup removes derived entries only and never authoritative feature state.'] }),
  'installation-deployment-recovery': contract({ configurationFields: [field('deploymentProfile', 'string', 'Supported local or VPS deployment topology.'), field('backupFreshnessSeconds', 'duration', 'Maximum acceptable age before upgrade or recovery gates block.')], validStates: ['installed', 'running', 'degraded', 'maintenance', 'recovering', 'rollback-ready'], persistenceRequirements: ['Exact SHA, component versions, migration head, configuration generation, and recovery evidence remain linked.'], restartAndRecovery: ['Restart follows the selected profile and proves one healthy instance before leaving recovery mode.'], cleanupBehavior: ['Decommission removes services and credentials only after export and recovery evidence are complete.'] }),
  'privacy-governance': contract({ configurationFields: [field('featureRetentionPolicies', 'object-list', 'Purpose, retention, export, erasure, and backup rules by feature.'), field('analyticsCohortMinimum', 'integer', 'Minimum cohort size for privacy-conscious aggregate analytics.')], validStates: ['policy-current', 'export-pending', 'erasure-pending', 'retention-blocked', 'completed'], persistenceRequirements: ['Governance decisions, subject scope, feature handlers, and completion evidence remain auditable.'], restartAndRecovery: ['Restart resumes pending export or erasure handlers without crossing guild or customer scope.'], cleanupBehavior: ['Completed erasure removes eligible data from active stores and schedules backup expiry implications.'] }),
  'music-playback': contract({ configurationFields: [field('lavalinkNode', 'identifier', 'Configured Lavalink node selected for playback.'), field('idleDisconnectSeconds', 'duration', 'Voice idle duration before policy disconnect.')], validStates: ['disconnected-empty', 'connected-idle', 'playing', 'paused', 'queue-advancing', 'node-recovering'], persistenceRequirements: ['Guild player, voice channel, current track, queue order, controls, and requester remain synchronized.'], restartAndRecovery: ['Node or bot restart restores a valid queue once and reconnects only when policy and listeners allow.'], cleanupBehavior: ['Stop clears the active track and queue; disconnect destroys the guild player and voice session exactly once.'] }),
};

export class MissingFeatureContractError extends Error {
  readonly featureId: string;

  constructor(featureId: string) {
    super(`Feature "${featureId}" does not declare an acceptance contract.`);
    this.name = 'MissingFeatureContractError';
    this.featureId = featureId;
  }
}

export function getFeatureContract(featureId: string): FeatureAcceptanceContract {
  const featureContract = FEATURE_CONTRACTS[featureId];
  if (!featureContract) {
    throw new MissingFeatureContractError(featureId);
  }
  return featureContract;
}
