/**
 * Database type definitions — MANUALLY MAINTAINED.
 *
 * V11 Audit M-6: The previous header claimed this was auto-generated by
 * `scripts/generate-db-types.ts`, but that script does not exist. The
 * types are hand-written and must be updated alongside migration changes.
 *
 * This file is the SINGLE SOURCE OF TRUTH for database column types.
 * If a column name doesn't exist here, it doesn't exist in the database.
 */

// ============================================================
// Helper Types & Constants (manually maintained)
// ============================================================

// Generic JSON type for JSONB columns
export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

// Two-phase privacy RPC results. Both purge functions return JSONB so callers
// must inspect purge_status instead of treating a successful RPC as completion.
export type PrivacyPurgeStatus = 'pending_role_cleanup' | 'completed';

export interface PrivacyPurgeRpcResult {
  [key: string]: Json;
  purge_status: PrivacyPurgeStatus;
  pending_role_cleanup_count: number;
}

export type PurgeMemberDataRpcResult = PrivacyPurgeRpcResult;
export type PurgeGuildDataRpcResult = PrivacyPurgeRpcResult;

// Auto-Mod Rule Config Types
export type AutoModRuleType =
  | 'word_filter'
  | 'link_filter'
  | 'invite_filter'
  | 'spam_filter'
  | 'duplicate_filter'
  | 'caps_filter'
  | 'mention_spam'
  | 'newline_spam';

export type AutoModAction = 'delete' | 'warn' | 'mute' | 'kick' | 'ban';

export interface WordFilterConfig {
  words: string[];
  matchMode: 'exact' | 'wildcard' | 'regex';
  caseSensitive: boolean;
}

export interface LinkFilterConfig {
  mode: 'whitelist' | 'blacklist';
  domains: string[];
}

export interface InviteFilterConfig {
  allowOwnServer: boolean;
}

export interface SpamFilterConfig {
  maxMessages: number;
  intervalSeconds: number;
}

export interface DuplicateFilterConfig {
  threshold: number;
  intervalSeconds: number;
}

export interface CapsFilterConfig {
  maxPercent: number;
  minLength: number;
}

export interface MentionSpamConfig {
  maxMentions: number;
}

export interface NewlineSpamConfig {
  maxNewlines: number;
}

export type AutoModRuleConfig =
  | WordFilterConfig
  | LinkFilterConfig
  | InviteFilterConfig
  | SpamFilterConfig
  | DuplicateFilterConfig
  | CapsFilterConfig
  | MentionSpamConfig
  | NewlineSpamConfig;

// Infraction Types
export type InfractionType = 'warn' | 'mute' | 'kick' | 'ban';

// Escalation Chain
export interface EscalationStep {
  threshold: number;
  action: 'warn' | 'mute' | 'kick' | 'ban';
  durationMinutes?: number;
  dmMember: boolean;
}

export const DEFAULT_ESCALATION_CHAIN: EscalationStep[] = [
  { threshold: 1, action: 'warn', dmMember: true },
  { threshold: 2, action: 'warn', dmMember: true },
  { threshold: 3, action: 'mute', durationMinutes: 60, dmMember: true },
  { threshold: 4, action: 'mute', durationMinutes: 1440, dmMember: true },
  { threshold: 5, action: 'kick', dmMember: true },
  { threshold: 6, action: 'ban', dmMember: true },
];

// Ticket Type Config
export interface TicketTypeConfig {
  id: string;
  label: string;
  emoji: string;
  color: 'blue' | 'grey' | 'green' | 'red';
  description?: string;
  categoryOverride?: string;
  managerRoleOverride?: string[];
  introMessageOverride?: string;
}

// Dashboard Permissions
export type DashboardPermission =
  | 'dashboard.full_access'
  | 'dashboard.view_analytics'
  | 'dashboard.manage_store'
  | 'dashboard.manage_products'
  | 'dashboard.manage_orders'
  | 'dashboard.manage_customers'
  | 'dashboard.manage_licenses'
  | 'dashboard.manage_moderation'
  | 'dashboard.manage_tickets'
  | 'dashboard.manage_automations'
  | 'dashboard.manage_server'
  | 'dashboard.manage_roles'
  | 'dashboard.manage_channels'
  | 'dashboard.manage_team'
  | 'dashboard.view_audit'
  | 'dashboard.view_diagnostics'
  | 'dashboard.manage_incidents'
  | 'dashboard.view_fraud'
  | 'dashboard.manage_fraud'
  | 'dashboard.view_workflows'
  | 'dashboard.manage_workflows'
  | 'dashboard.undo_changes'
  | 'dashboard.manage_economy';

// Fraud Types
export type FraudSignalType =
  | 'velocity'
  | 'device_abuse'
  | 'chargeback'
  | 'ip_mismatch'
  | 'key_sharing'
  | 'payment_pattern';

export type FraudSeverity = 'low' | 'medium' | 'high' | 'critical';
export type FraudSignalStatus = 'open' | 'investigating' | 'confirmed' | 'dismissed' | 'auto_resolved';

export type FraudRuleType =
  | 'velocity_limit'
  | 'device_limit'
  | 'ip_block'
  | 'amount_threshold'
  | 'pattern_match';

// Incident Types
export type IncidentSeverity = 'info' | 'warning' | 'critical' | 'outage';
export type IncidentStatus = 'open' | 'investigating' | 'identified' | 'monitoring' | 'resolved';

// DLQ Types
export type DLQStatus = 'pending' | 'retrying' | 'exhausted' | 'resolved' | 'discarded';

// Admin Change Types
export type BlastRadius = 'low' | 'medium' | 'high' | 'critical';


// ============================================================
// Row Types — auto-generated from SQL migrations
// ============================================================

// — Core —

export interface DbUser {
  id: string;
  discord_id: string;
  discord_username: string;
  avatar_url: string | null;
  email: string | null;
  is_owner: boolean;
  created_at: string;
  updated_at: string;
}

export interface DbGuild {
  id: string;
  name: string;
  icon_url: string | null;
  owner_discord_id: string;
  bot_joined_at: string;
  setup_completed: boolean;
  setup_confirmed_at: string | null;
  bot_role_id: string | null;
  bot_role_position: number | null;
  created_at: string;
  updated_at: string;
  total_roles: number | null;
}

export interface DbGuildConfig {
  guild_id: string;
  member_role_id: string | null;
  onboarding_enabled: boolean;
  interest_role_mapping: Record<string, string>;
  returning_member_skip_welcome_dm: boolean;
  returning_member_restore_entitlements: boolean;
  returning_member_restore_levels: boolean;
  welcome_enabled: boolean;
  welcome_channel_id: string | null;
  welcome_message: string | null;
  welcome_card_enabled: boolean;
  welcome_card_background: string | null;
  welcome_dm_enabled: boolean;
  welcome_dm_message: string | null;
  welcome_auto_roles: string[];
  goodbye_enabled: boolean;
  goodbye_channel_id: string | null;
  goodbye_message: string | null;
  mod_log_channel_id: string | null;
  escalation_chain: EscalationStep[];
  infraction_expiry_days: number;
  ticket_transcript_enabled: boolean;
  ticket_dm_transcript: boolean;
  levels_enabled: boolean;
  xp_min: number;
  xp_max: number;
  xp_cooldown_seconds: number;
  voice_xp_enabled: boolean;
  voice_xp_per_interval: number;
  voice_xp_interval_minutes: number;
  level_up_channel_id: string | null;
  level_up_message: string;
  xp_multiplier_mode: 'highest' | 'additive';
  xp_channel_mode: 'blacklist' | 'whitelist';
  xp_channel_list: string[];
  rank_card_accent_color: number;
  rank_card_background: string | null;
  music_enabled: boolean;
  dj_role_id: string | null;
  music_default_volume: number;
  music_auto_leave_minutes: number;
  music_auto_destroy_minutes: number;
  store_enabled: boolean;
  grace_period_days: number;
  stats_enabled: boolean;
  stats_update_interval_minutes: number;
  temp_channels_enabled: boolean;
  scheduled_messages_enabled: boolean;
  giveaways_enabled: boolean;
  sync_enabled: boolean;
  sync_interval_minutes: number;
  sync_auto_repair: boolean;
  sync_auto_repair_everyone: boolean;
  updated_at: string;
  paypal_enabled: boolean;
  custom_bot_statuses: string[];
  onboarding_config: Record<string, unknown> | null;
  // V17 Behavioral Audit additions
  no_xp_role_id: string | null;
  anti_raid_enabled: boolean;
  anti_raid_join_threshold: number;
  anti_raid_join_window_seconds: number;
  anti_raid_account_age_days: number;
  anti_raid_action: 'kick' | 'ban' | 'lockdown';
  anti_raid_log_channel_id: string | null;
  starboard_enabled: boolean;
  starboard_channel_id: string | null;
  starboard_threshold: number;
  starboard_emoji: string;
  starboard_self_star: boolean;
  message_log_enabled: boolean;
  message_log_channel_id: string | null;
  // V31: Economy Core
  economy_enabled: boolean;
  currency_name: string;
  currency_emoji: string;
  economy_starting_balance: number;
  economy_daily_amount: number;
  economy_weekly_amount: number;
  economy_monthly_amount: number;
  economy_streak_bonus_pct: number;
  economy_work_cooldown_seconds: number;
  economy_work_min: number;
  economy_work_max: number;
  economy_crime_success_pct: number;
  economy_crime_fine_pct: number;
  economy_crime_min: number;
  economy_crime_max: number;
  economy_chat_income_enabled: boolean;
  economy_chat_income_min: number;
  economy_chat_income_max: number;
  economy_chat_income_cooldown_seconds: number;
  economy_rob_enabled: boolean;
  economy_rob_success_pct: number;
  economy_rob_fine_pct: number;
  economy_heist_enabled: boolean;
  economy_heist_min_participants: number;
  economy_heist_max_participants: number;
  economy_heist_join_window_secs: number;
  economy_heist_cooldown_seconds: number;
  economy_heist_base_payout: number;
  economy_heist_success_base_pct: number;
  economy_heist_entry_fee: number;
  economy_passive_mode_allowed: boolean;
  economy_pay_tax_pct: number;
  economy_max_wallet: number;
  economy_max_bank: number;
  economy_log_channel_id: string | null;

  // V31 PR #43 — Gathering, Crafting, Farming
  economy_gathering_enabled: boolean;
  economy_gathering_cooldown_seconds: number;
  economy_crafting_enabled: boolean;
  economy_crafting_cooldown_seconds: number;
  economy_farming_enabled: boolean;
  economy_farm_grid_size: number;
  economy_farming_wilt_enabled: boolean;
  economy_fertilizer_time_reduction_pct: number;
  // Fishing
  economy_fishing_enabled: boolean;
  economy_fishing_cooldown_seconds: number;
  economy_fishing_junk_chance_pct: number;
  economy_fishing_treasure_chance_pct: number;
  // Adventures
  economy_adventures_enabled: boolean;
  economy_adventure_daily_limit: number;
  economy_adventure_ticket_cost: number;
  economy_adventure_max_scenes: number;
  // Market
  economy_market_enabled: boolean;
  economy_market_fee_pct: number;
  economy_market_listing_days: number;
  economy_market_max_listings: number;
  // PR #45 — Trivia
  economy_trivia_enabled: boolean;
  economy_trivia_cooldown_seconds: number;
  economy_trivia_base_payout: number;
  economy_trivia_streak_multiplier_pct: number;
  economy_trivia_hard_multiplier: number;
  // Scheduled / hosted trivia cadence
  economy_trivia_schedule_enabled: boolean;
  economy_trivia_schedule_interval_minutes: number;
  economy_trivia_schedule_channel_id: string | null;
  economy_trivia_schedule_category: string | null;
  economy_trivia_schedule_difficulty: string | null;
  economy_trivia_schedule_last_run_at: string | null;
  // PR #45 — Mini-Games
  economy_games_enabled: boolean;
  economy_daily_loss_limit: number;
  economy_coinflip_max_bet: number;
  economy_slots_max_bet: number;
  economy_blackjack_max_bet: number;
  // PR #45 — Lottery
  economy_lottery_enabled: boolean;
  economy_lottery_schedule: string;
  economy_lottery_ticket_price: number;
  economy_lottery_max_tickets: number;
  // PR #45 — Polls & Predictions
  polls_enabled: boolean;
  predictions_enabled: boolean;

  // PR #46 — Pets, Quests, Achievements, Prestige
  economy_pets_enabled: boolean;
  economy_pet_decay_rate: number;
  economy_pet_decay_interval_hours: number;
  economy_pet_low_stat_threshold: number;
  economy_pet_notify_owner: boolean;
  economy_pet_battle_enabled: boolean;
  economy_pet_prestige_enabled: boolean;
  economy_pet_feed_cost: number;
  economy_pet_train_cost: number;
  economy_quests_enabled: boolean;
  economy_daily_quest_count: number;
  economy_weekly_quest_count: number;
  economy_quest_reward_base: number;
  economy_achievements_enabled: boolean;
  economy_prestige_enabled: boolean;
  economy_prestige_multiplier_pct: number;
  economy_prestige_min_level: number;
  economy_prestige_min_net_worth: number;

  // V53 Phase 2 Observability / retention / ticketing additions
  alert_channel_id: string | null;
  anti_raid_ban_delete_seconds: number;
  data_retention_days: number;
  ticket_satisfaction_survey: boolean;
}

export interface DbInstanceSettings {
  key: string;
  value: string | null;
  section: string;
  updated_at: string;
}

// — Members —

export interface DbMember {
  guild_id: string;
  discord_id: string;
  username: string;
  avatar_url: string | null;
  roles: string[];
  joined_at: string;
  left_at: string | null;
  onboarding_completed: boolean;
  is_returning: boolean;
  member_number: number;
  total_time_seconds: number;
  created_at: string;
  updated_at: string;
}

// — Templates & Server Structure —

export interface DbRoleTemplate {
  id: string;
  guild_id: string | null;
  name: string;
  tier: 'everyone' | 'cosmetic' | 'member' | 'moderator' | 'admin' | 'custom';
  description: string | null;
  permissions: number;
  permission_details: Record<string, unknown>;
  is_builtin: boolean;
  base_template_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbChannelTemplate {
  id: string;
  guild_id: string | null;
  name: string;
  description: string | null;
  target_channel_type: 'text' | 'voice' | 'stage' | 'forum' | 'announcement';
  overrides: Record<string, unknown>;
  is_builtin: boolean;
  base_template_id: string | null;
  created_at: string;
  updated_at: string;
}

// DbServerTemplate removed in v53 — table dropped (never referenced by bot or dashboard)

export interface DbGuildDesiredState {
  guild_id: string;
  roles: Record<string, unknown>[];
  channels: Record<string, unknown>[];
  permission_map: Record<string, unknown>;
  applied_at: string | null;
  last_sync_at: string | null;
  drift_detected: boolean;
  drift_details: Record<string, unknown> | null;
  updated_at: string;
}

export interface DbDiscordIdMap {
  guild_id: string | null;
  entity_type: 'role' | 'channel' | 'category';
  template_key: string;
  discord_id: string;
}

export interface DbGuildLiveState {
  guild_id: string;
  roles: Record<string, unknown>[];
  channels: Record<string, unknown>[];
  categories: Record<string, unknown>[];
  member_count: number;
  /** JSONB array of member snapshots for dashboard MemberPicker (V14). */
  members: GuildMemberSnapshot[] | null;
  bot_role_id: string | null;
  bot_role_position: number;
  onboarding_enabled: boolean;
  onboarding_prompts: Record<string, unknown>[];
  snapshot_at: string;
}

/** Shape of each member entry in guild_live_state.members JSONB. */
export interface GuildMemberSnapshot {
  id: string;
  username: string;
  display_name: string | null;
  avatar: string | null;
  bot: boolean;
  joined_at: string | null;
  roles: string[];
}

// — Reaction Roles —

export interface DbReactionRole {
  id: string;
  guild_id: string | null;
  channel_id: string;
  message_id: string;
  emoji: string;
  role_id: string;
  exclusive_group: string | null;
  require_role: string | null;
  require_level: number | null;
  max_per_group: number | null;
  remove_on_unreact: boolean;
  log_actions: boolean;
  active: boolean;
  created_at: string;
}

// — Moderation —

export interface DbAutomodRule {
  id: string;
  guild_id: string | null;
  name: string;
  type: 'word_filter' | 'link_filter' | 'invite_filter' | 'spam_filter' | 'duplicate_filter' | 'caps_filter' | 'mention_spam' | 'newline_spam';
  enabled: boolean;
  config: AutoModRuleConfig;
  action: 'delete' | 'warn' | 'mute' | 'kick' | 'ban';
  mute_duration_minutes: number | null;
  exempt_roles: string[];
  exempt_channels: string[];
  log_to_mod_channel: boolean;
  priority: number;
  created_at: string;
  updated_at: string;
  sync_to_discord: boolean;
}

export interface DbInfraction {
  id: string;
  guild_id: string | null;
  member_id: string;
  moderator_id: string;
  type: 'warn' | 'mute' | 'kick' | 'ban';
  reason: string;
  automod_rule_id: string | null;
  duration_minutes: number | null;
  active: boolean;
  pardoned: boolean;
  pardoned_by: string | null;
  pardoned_at: string | null;
  expires_at: string | null;
  created_at: string;
}

export interface DbMessageReport {
  id: string;
  guild_id: string;
  reporter_id: string;
  channel_id: string;
  message_id: string;
  message_author: string;
  reason: string;
  message_content: string | null;
  status: string;
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
}

// — Ticketing —

export interface DbTicketPanel {
  id: string;
  guild_id: string | null;
  name: string;
  channel_id: string;
  message_id: string | null;
  panel_message: Record<string, unknown>;
  input_mode: 'buttons' | 'dropdown';
  ticket_types: TicketTypeConfig[];
  manager_roles: string[];
  open_category_id: string;
  closed_category_id: string | null;
  transcript_channel_id: string | null;
  dm_transcript_to_creator: boolean;
  max_open_per_user: number;
  introduction_message: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
  forum_config: Record<string, unknown> | null;
  // V19 Audit: added missing schema fields
  intake_form_enabled: boolean;
  intake_form_fields: Json[] | null;
}

export interface DbTicket {
  id: string;
  guild_id: string | null;
  panel_id: string | null;
  channel_id: string | null;
  ticket_number: number;
  creator_id: string;
  type: string;
  claimed_by: string | null;
  status: 'open' | 'claimed' | 'closed' | 'deleted';
  closed_by: string | null;
  close_reason: string | null;
  transcript_path: string | null;
  message_count: number;
  created_at: string;
  updated_at: string;
  closed_at: string | null;
  deleted_at: string | null;
  inactivity_warned: boolean;
  subject: string | null;
  description: string | null;
  is_forum_ticket: boolean;
  forum_thread_id: string | null;
  // V19 Audit: added missing schema fields
  feedback_rating: number | null;
  feedback_comment: string | null;
}

export interface DbTicketTranscript {
  id: string;
  guild_id: string | null;
  ticket_id: string | null;
  ticket_number: number;
  creator_id: string;
  closed_by_id: string;
  message_count: number;
  participant_ids: string[];
  html_content: string;
  created_at: string;
}

export interface DbTicketMetric {
  ticket_id: string;
  guild_id: string;
  resolution_time_ms: number;
  resolved_at: string;
}

// — Automations —

export interface DbAutomation {
  id: string;
  guild_id: string | null;
  name: string;
  description: string | null;
  trigger_type: string;
  trigger_config: Record<string, unknown>;
  target_user_ids: string[];
  target_channel_ids: string[];
  exclude_user_ids: string[];
  exclude_channel_ids: string[];
  conditions: Record<string, unknown>[];
  actions: Record<string, unknown>[];
  enabled: boolean;
  execution_count: number;
  last_executed_at: string | null;
  created_at: string;
  updated_at: string;
  rate_limit_per_user: number | null;
  rate_limit_window_seconds: number | null;
}

export interface DbAutomationExecution {
  id: string;
  automation_id: string | null;
  guild_id: string | null;
  triggered_by: string;
  trigger_event: string;
  conditions_passed: boolean;
  actions_executed: number;
  actions_failed: number;
  errors: Record<string, unknown>[];
  duration_ms: number | null;
  created_at: string;
}

export interface DbCustomCommand {
  id: string;
  guild_id: string | null;
  name: string;
  description: string;
  actions: Record<string, unknown>[];
  allowed_roles: string[];
  allowed_channels: string[];
  denied_roles: string[];
  denied_channels: string[];
  cooldown_seconds: number;
  ephemeral: boolean;
  enabled: boolean;
  discord_command_id: string | null;
  created_at: string;
  updated_at: string;
}

// — Embeds —

export interface DbEmbedConfig {
  id: string;
  guild_id: string | null;
  name: string;
  title: string | null;
  description: string | null;
  color: number | null;
  fields: Record<string, unknown>[];
  image_url: string | null;
  thumbnail_url: string | null;
  footer_text: string | null;
  footer_icon_url: string | null;
  author_name: string | null;
  author_url: string | null;
  author_icon_url: string | null;
  include_timestamp: boolean;
  use_components_v2: boolean;
  components_v2_data: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}

// — Levels & XP —

export interface DbMemberLevel {
  guild_id: string | null;
  member_id: string;
  xp: number;
  level: number;
  total_messages: number;
  voice_minutes: number;
  last_xp_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbLevelReward {
  id: string;
  guild_id: string | null;
  level: number;
  role_id: string;
  remove_at_level: number | null;
  announce: boolean;
  created_at: string;
}

export interface DbXpMultiplier {
  id: string;
  guild_id: string | null;
  role_id: string;
  multiplier: number;
  created_at: string;
}

export interface DbMemberRankSettings {
  guild_id: string | null;
  member_id: string;
  background_url: string | null;
  background_storage_path: string | null;
  accent_color: number | null;
  progress_bar_color: number | null;
  overlay_opacity: number;
  font_color_override: 'light' | 'dark' | null;
  created_at: string;
  updated_at: string;
}

// — Temp Channels & Stats —

export interface DbTempChannelHub {
  id: string;
  guild_id: string | null;
  hub_channel_id: string;
  category_id: string;
  naming_format: string;
  default_user_limit: number;
  default_bitrate: number;
  keep_alive_minutes: number;
  allow_text_channel: boolean;
  moderator_roles: string[];
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface DbActiveTempChannel {
  channel_id: string;
  text_channel_id: string | null;
  guild_id: string | null;
  hub_id: string | null;
  owner_id: string;
  created_at: string;
}

export interface DbStatsChannel {
  id: string;
  guild_id: string | null;
  channel_id: string | null;
  stat_type: 'total_members' | 'online_members' | 'bot_count' | 'role_count' | 'channel_count' | 'premium_members' | 'active_tickets' | 'total_xp_earned' | 'highest_level' | 'custom_counter';
  stat_config: Record<string, unknown>;
  name_format: string;
  active: boolean;
  last_value: string | null;
  last_updated_at: string | null;
  created_at: string;
  updated_at: string;
}

// — Scheduled Messages —

export interface DbScheduledMessage {
  id: string;
  guild_id: string | null;
  name: string;
  channel_id: string;
  message: string | null;
  embed_config_id: string | null;
  cron_expression: string;
  timezone: string;
  start_date: string | null;
  end_date: string | null;
  max_sends: number | null;
  current_sends: number;
  active: boolean;
  last_sent_at: string | null;
  created_at: string;
  updated_at: string;
}

// — Commerce — Products —

export interface DbProduct {
  id: string;
  guild_id: string | null;
  name: string;
  description: string | null;
  type: 'one_time' | 'subscription';
  delivery_type: 'file' | 'link' | 'access_pass' | 'license_key' | 'mixed';
  paypal_product_id: string | null;
  price_cents: number;
  currency: string;
  granted_role_ids: string[];
  granted_channel_ids: string[];
  active: boolean;
  sort_order: number;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface DbCommerceProductTempRoleConfig {
  id: string;
  product_id: string;
  guild_id: string;
  role_id: string;
  duration_seconds: number;
  created_at: string;
  updated_at: string;
}

export interface DbCommerceLegacySubscriptionGrantContract {
  order_id: string;
  source_queue_id: string;
  guild_id: string;
  customer_id: string;
  discord_id: string;
  product_id: string;
  product_name: string;
  order_number: string;
  plan_id: string;
  paypal_subscription_id: string;
  paypal_plan_id: string;
  amount_cents: number;
  currency: string;
  granted_role_ids_snapshot: string[];
  granted_channel_ids_snapshot: string[];
  persisted_at: string;
}

export type CommerceRoleMetadataMigrationIssueType =
  | 'invalid_role_id'
  | 'invalid_duration'
  | 'orphan_duration'
  | 'unsupported_product_type'
  | 'ambiguous_permanent_history'
  | 'ambiguous_historical_role'
  | 'invalid_historical_roles';

export interface DbCommerceRoleMetadataMigrationIssue {
  id: string;
  product_id: string;
  guild_id: string;
  role_id: string | null;
  issue_type: CommerceRoleMetadataMigrationIssueType;
  details: Record<string, unknown>;
  resolved_at: string | null;
  created_at: string;
}

export interface DbCommerceTempRoleMigrationIssue {
  id: string;
  temp_role_grant_id: string;
  guild_id: string;
  user_id: string;
  role_id: string;
  source: string | null;
  source_id: string | null;
  issue_type: 'missing_order_provenance';
  resolved_at: string | null;
  created_at: string;
}

export interface DbTempRoleGrant {
  id: string;
  guild_id: string;
  user_id: string;
  role_id: string;
  expires_at: string;
  source: string;
  source_id: string | null;
  created_at: string;
  order_id: string | null;
  grant_status: 'pending' | 'applied' | 'removed';
  duration_seconds: number | null;
  remove_on_expiry: boolean;
  applied_at: string | null;
  attempts: number;
  last_error: string | null;
  updated_at: string;
}

export interface DbProductFile {
  id: string;
  product_id: string | null;
  name: string;
  description: string | null;
  file_path: string | null;
  external_url: string | null;
  file_size_bytes: number | null;
  mime_type: string | null;
  download_count: number;
  sort_order: number;
  created_at: string;
  // V19 Audit: added missing schema fields
  display_name: string | null;
  file_name: string | null;
  guild_id: string | null;
  size_bytes: number | null;
  storage_bucket: string | null;
  storage_path: string | null;
  version: string | null;
}

export interface DbPlan {
  id: string;
  product_id: string | null;
  guild_id: string | null;
  name: string;
  paypal_plan_id: string | null;
  interval_unit: 'DAY' | 'WEEK' | 'MONTH' | 'YEAR';
  interval_count: number;
  price_cents: number;
  currency: string;
  trial_days: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}

// — Commerce — Customers —

export interface DbCustomer {
  id: string;
  user_id: string | null;
  guild_id: string | null;
  discord_id: string;
  discord_username: string;
  paypal_customer_id: string | null;
  email: string | null;
  first_purchase_at: string | null;
  total_spent_cents: number;
  total_orders: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbPromotion {
  id: string;
  guild_id: string | null;
  name: string;
  type: 'percentage' | 'fixed_amount';
  value: number;
  coupon_code: string | null;
  applies_to_product_ids: string[];
  applies_to_plan_ids: string[];
  start_date: string | null;
  end_date: string | null;
  max_uses: number | null;
  current_uses: number;
  min_purchase_cents: number | null;
  first_purchase_only: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

// — Commerce — Orders —

export interface DbOrder {
  id: string;
  order_number: string;
  customer_id: string | null;
  guild_id: string | null;
  product_id: string | null;
  plan_id: string | null;
  paypal_order_id: string | null;
  paypal_subscription_id: string | null;
  amount_cents: number;
  currency: string;
  discount_cents: number;
  promotion_id: string | null;
  source: 'purchase' | 'giveaway' | 'manual' | 'automation';
  status: 'pending' | 'completed' | 'refunded' | 'disputed' | 'cancelled' | 'pending_review';
  created_at: string;
  updated_at: string;
  granted_role_ids_snapshot: string[];
  granted_channel_ids_snapshot: string[];
  temporary_role_grants_snapshot: Array<{
    role_id: string;
    duration_seconds: number;
  }>;
  grant_snapshot_frozen_at: string | null;
}

// — Commerce — Licensing —

export interface DbLicenseKey {
  id: string;
  order_id: string | null;
  customer_id: string | null;
  product_id: string | null;
  guild_id: string | null;
  key_hash: string;
  key_prefix: string;
  key_suffix: string;
  bound_discord_id: string;
  status: 'pending_activation' | 'active' | 'expired' | 'revoked' | 'suspended';
  activated_at: string | null;
  expires_at: string | null;
  revoked_at: string | null;
  revocation_reason: string | null;
  created_at: string;
  updated_at: string;
  failed_attempts: number;
  last_failed_at: string | null;
  commerce_required_order_status: 'completed' | null;
}

export interface DbEntitlement {
  id: string;
  customer_id: string | null;
  guild_id: string | null;
  product_id: string | null;
  plan_id: string | null;
  license_key_id: string | null;
  order_id: string | null;
  type: 'one_time' | 'subscription';
  status: 'active' | 'expired' | 'suspended' | 'cancelled' | 'pending' | 'grace_period';
  source: 'purchase' | 'giveaway' | 'manual' | 'automation';
  granted_role_ids: string[];
  granted_channel_ids: string[];
  grace_period_ends_at: string | null;
  starts_at: string;
  expires_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
  commerce_required_order_status: 'completed' | null;
}

export interface DbProductLicenseConfig {
  product_id: string;
  license_mode: 'portal_only' | 'portal_watermark' | 'embedded' | 'access_pass';
  max_devices: number;
  heartbeat_interval_seconds: number;
  offline_grace_period_seconds: number;
  feature_flags: string[];
  tier: string | null;
  watermark_config: Record<string, unknown> | null;
  require_discord_guild_membership: boolean;
  created_at: string;
  updated_at: string;
  // V19 Audit: added missing schema fields
  device_policy: string | null;
}

export interface DbLicenseSession {
  id: string;
  license_key_id: string | null;
  device_fingerprint: string;
  device_name: string | null;
  app_version: string | null;
  ip_address: string | null;
  active: boolean;
  first_seen_at: string;
  last_seen_at: string;
  deactivated_at: string | null;
  deactivation_reason: 'user_deactivated' | 'admin_revoked' | 'device_limit' | 'heartbeat_timeout' | 'entitlement_revoked' | null;
  commerce_required_license_status: 'active' | null;
}

export interface DbLicenseValidation {
  id: string;
  license_key_id: string | null;
  product_id: string | null;
  device_fingerprint: string | null;
  result:
    | 'valid'
    | 'invalid_key'
    | 'expired'
    | 'suspended'
    | 'revoked'
    | 'over_device_limit'
    | 'product_mismatch'
    | 'cancelled'
    | 'pending'
    | 'grace_period'
    | 'unavailable'
    | 'rate_limited'
    | 'session_invalidated'
    | 'device_fingerprint_required';
  ip_address: string | null;
  app_version: string | null;
  created_at: string;
}

// — Commerce — Payments —

export interface DbPayment {
  id: string;
  order_id: string | null;
  customer_id: string | null;
  guild_id: string | null;
  paypal_payment_id: string | null;
  paypal_event_id: string | null;
  amount_cents: number;
  currency: string;
  status: 'completed' | 'refunded' | 'reversed' | 'pending' | 'failed';
  created_at: string;
  // V19 Audit: added missing schema fields
  provider: string | null;
  paypal_resource_type: 'capture' | 'sale' | null;
  commerce_required_order_status: 'completed' | 'refunded' | null;
  commerce_settled_capture_order_id: string | null;
}

// — Commerce — Giveaways —

export interface DbGiveaway {
  id: string;
  guild_id: string | null;
  channel_id: string;
  message_id: string | null;
  prize: string;
  prize_product_id: string | null;
  prize_license_count: number;
  winner_count: number;
  ends_at: string;
  required_role_id: string | null;
  required_level: number | null;
  required_entitlement_product_id: string | null;
  entries: string[];
  winners: string[];
  status: 'active' | 'ended' | 'cancelled' | 'paused';
  ended_at: string | null;
  created_by: string;
  created_at: string;
}

// — Audit & Operations —

export interface DbAuditLog {
  id: string;
  guild_id: string | null;
  timestamp: string;
  actor_type: string;
  actor_id: string;
  action: string;
  target_type: string | null;
  target_id: string | null;
  details: Record<string, unknown>;
  before_state: Record<string, unknown> | null;
  after_state: Record<string, unknown> | null;
  success: boolean;
  error_message: string | null;
  // V19 Audit: added missing schema fields
  category: string | null;
  correlation_id: string | null;
}

export interface DbWebhookEvent {
  event_id: string;
  event_type: string;
  processed_at: string;
  payload: Record<string, unknown>;
  result: 'success' | 'error' | 'duplicate' | null;
  error_details: string | null;
  // V19 Audit: added missing schema fields
  guild_id: string;
  replay_count: number;
  replayed_at: string | null;
}

export interface DbBotDiagnostics {
  guild_id: string;
  uptime_seconds: number;
  memory_rss_mb: number;
  memory_heap_mb: number;
  lavalink_nodes: Record<string, unknown>[];
  valkey_connected: boolean;
  valkey_memory_mb: number;
  guild_member_count: number;
  active_voice_connections: number;
  scheduled_message_count: number;
  automation_count: number;
  discord_ws_ping: number;
  snapshot_at: string;
  type: string;
  data: Record<string, unknown> | null;
}

export interface DbBotActionQueue {
  id: string;
  guild_id: string;
  action: string;
  payload: Record<string, unknown>;
  status: 'staged' | 'pending' | 'processing' | 'completed' | 'failed';
  // 20260710020000: processing lane — stamped by a BEFORE INSERT trigger
  // from `action` (commerce = paid-store work, prioritized over game).
  lane: 'commerce' | 'game';
  idempotency_key: string | null;
  result: Record<string, unknown> | null;
  error_message: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
  // Retry / backoff bookkeeping. 20260518000001_missing_tables.sql adds these
  // to the pre-existing table via unconditional `ALTER ... ADD COLUMN IF NOT
  // EXISTS`, so they DO exist; retry_count was added in 20260524000000 (V48).
  // next_retry_at is the receipt-retry backoff schedule (PR #265) and the
  // lane sweep (PR #275) filters on it — actively used, never dropped.
  action_type: string | null;
  attempts: number;
  max_attempts: number;
  retry_count: number;
  error: string | null;
  processed_at: string | null;
  next_retry_at: string | null;
}

// — Reconciliation —

export interface DbReconciliationRun {
  id: string;
  guild_id: string | null;
  started_at: string;
  completed_at: string | null;
  trigger: 'scheduled' | 'manual' | 'startup';
  status: 'running' | 'completed' | 'failed';
  findings: Record<string, unknown>;
  fixes_applied: Record<string, unknown>;
  error_message: string | null;
}

export interface DbAlert {
  id: string;
  guild_id: string;
  alert_type: string;
  severity: string;
  title: string;
  message: string | null;
  details: Record<string, unknown> | null;
  acknowledged: boolean;
  acknowledged_at: string | null;
  acknowledged_by: string | null;
  auto_resolved: boolean;
  resolved_at: string | null;
  created_at: string;
  // V19 Audit: added missing schema fields
  metadata: Record<string, unknown> | null;
  resolved: boolean;
  updated_at: string;
}

// — Dashboard RBAC —

export interface DbDashboardRole {
  id: string;
  guild_id: string;
  name: string;
  description: string | null;
  permissions: DashboardPermission[];
  is_system: boolean;
  created_at: string;
  updated_at: string;
  priority: number;
}

export interface DbDashboardUserRole {
  id: string;
  guild_id: string;
  discord_id: string;
  role_id: string;
  assigned_at: string;
  assigned_by: string | null;
  created_at: string;
  // V19 Audit: added missing schema fields
  granted_by: string | null;
  user_id: string | null;
}

// — Customer Portal —

export interface DbPortalSession {
  id: string;
  guild_id: string;
  customer_id: string | null;
  discord_id: string;
  /** @deprecated V22 — session_token is now nullable; all code uses token_hash. */
  session_token: string | null;
  ip_address: string | null;
  user_agent: string | null;
  expires_at: string;
  created_at: string;
  token_hash: string | null;
  revoked: boolean;
  last_used_at: string;
}

// — Fraud Controls —

export interface DbFraudSignal {
  id: string;
  guild_id: string;
  order_id: string | null;
  customer_id: string | null;
  discord_id: string | null;
  signal_type: string;
  severity: string;
  created_at: string;
  entity_type: string | null;
  entity_id: string | null;
  description: string | null;
  evidence: Record<string, unknown>;
  status: string;
  auto_action: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
  resolution_note: string | null;
  updated_at: string;
  last_observed_at: string;
  // V19 Audit: added missing schema fields
  action: string | null;
  details: Record<string, unknown> | null;
  resolved: boolean;
}

export interface DbFraudRule {
  id: string;
  guild_id: string;
  name: string;
  description: string | null;
  rule_type: string;
  config: Record<string, unknown>;
  action: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  auto_action: string;
  last_triggered: string | null;
  trigger_count: number;
}

// — Incidents —

export interface DbIncident {
  id: string;
  guild_id: string;
  title: string;
  description: string | null;
  severity: string;
  category: string;
  status: string;
  assigned_to: string | null;
  created_by: string;
  resolved_at: string | null;
  resolved_by: string | null;
  resolution: string | null;
  created_at: string;
  updated_at: string;
  incident_number: number | null;
  source: string | null;
  source_ref_id: string | null;
  started_at: string;
  identified_at: string | null;
  duration_seconds: number | null;
  impact_summary: string | null;
  root_cause: string | null;
}

export interface DbIncidentEvent {
  id: string;
  incident_id: string;
  event_type: string;
  actor_id: string;
  details: Record<string, unknown> | null;
  created_at: string;
  message: string | null;
  metadata: Record<string, unknown>;
}

// — DLQ & Workflows —

export interface DbDeadLetterItem {
  id: string;
  guild_id: string;
  event_type: string | null;
  action_type: string | null;
  payload: Record<string, unknown>;
  error: string | null;
  error_message: string | null;
  error_stack: string | null;
  retry_count: number;
  last_retry_at: string | null;
  max_retries: number;
  source: string | null;
  source_type: string | null;
  source_id: string | null;
  status: string;
  failure_count: number;
  first_failed_at: string | null;
  last_failed_at: string | null;
  reprocessed: boolean;
  reprocessed_at: string | null;
  created_at: string;
  resolved_at: string | null;
  resolved_by: string | null;
  resolution_note: string | null;
}

export interface DbWorkflowEvent {
  id: string;
  guild_id: string;
  automation_id: string | null;
  execution_id: string | null;
  event_type: string;
  step_name: string | null;
  input_data: Record<string, unknown> | null;
  output_data: Record<string, unknown> | null;
  error: string | null;
  duration_ms: number | null;
  created_at: string;
  correlation_id: string | null;
  error_message: string | null;
  parent_event_id: string | null;
  payload: Record<string, unknown>;
  result: 'success' | 'error' | 'skipped' | 'pending' | null;
  source: string | null;
}

// — Admin Changes —

export interface DbAdminChange {
  id: string;
  guild_id: string;
  actor_id: string;
  action: string;
  target_type: string;
  target_id: string;
  before_state: Record<string, unknown> | null;
  after_state: Record<string, unknown> | null;
  description: string | null;
  is_undoable: boolean;
  is_undone: boolean;
  undone_at: string | null;
  undone_by: string | null;
  blast_radius: string;
  requires_confirmation: boolean;
  undo_payload: Record<string, unknown> | null;
  undo_change_id: string | null;
  created_at: string;
  // V19 Audit: added missing schema fields
  change_type: string | null;
  target_table: string | null;
  undone: boolean;
}

// — Sync —

export interface DbSyncAction {
  id: string;
  guild_id: string;
  action_type: string;
  target_type: string;
  target_id: string | null;
  details: Record<string, unknown> | null;
  status: string;
  applied_at: string | null;
  created_at: string;
  // V19 Audit: added missing schema fields
  action: string | null;
  drift_item: Record<string, unknown> | null;
}

// ── V31: Economy Core ───────────────────────────────────────

export interface DbEconomyWallet {
  guild_id: string;
  user_id: string;
  wallet: number;
  bank: number;
  bank_max: number;
  passive: boolean;
  total_earned: number;
  total_spent: number;
  created_at: string;
  updated_at: string;
  // V53 ban/leave cleanup — suspended blocks economy commands & targeting
  suspended: boolean;
  suspended_at: string | null;
  suspended_reason: string | null;
}

export type EconomyTransactionType =
  | 'daily'
  | 'weekly'
  | 'monthly'
  | 'work'
  | 'crime'
  | 'beg'
  | 'search'
  | 'chat_income'
  | 'role_income'
  | 'pay_send'
  | 'pay_receive'
  | 'rob_success'
  | 'rob_fail'
  | 'rob_victim'
  | 'heist_win'
  | 'heist_fail'
  | 'shop_buy'
  | 'shop_sell'
  | 'deposit'
  | 'withdraw'
  | 'admin_add'
  | 'admin_remove'
  | 'admin_set';

export interface DbEconomyTransaction {
  id: string;
  guild_id: string;
  user_id: string;
  type: EconomyTransactionType;
  amount: number;
  balance_after: number;
  description: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export type EconomyItemCategory =
  | 'Tools'
  | 'Bait'
  | 'Seeds'
  | 'Materials'
  | 'Consumables'
  | 'Roles'
  | 'Cosmetics'
  | 'Lootboxes';

export interface EconomyItemUseEffect {
  type: 'xp_boost' | 'coin_boost' | 'padlock' | 'alarm' | 'adventure_ticket' | 'role_grant' | 'custom';
  duration_minutes?: number;
  multiplier?: number;
  role_id?: string;
  custom_data?: Record<string, unknown>;
}

export interface DbEconomyItem {
  id: string;
  guild_id: string;
  name: string;
  description: string | null;
  emoji: string;
  category: EconomyItemCategory;
  price: number;
  sell_price: number;
  stock: number | null;
  max_per_user: number | null;
  require_role_id: string | null;
  grant_role_id: string | null;
  usable: boolean;
  use_effect: EconomyItemUseEffect | null;
  durability: number | null;
  tradeable: boolean;
  active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface DbEconomyInventory {
  id: string;
  guild_id: string;
  user_id: string;
  item_id: string;
  quantity: number;
  durability_remaining: number | null;
  acquired_at: string;
  updated_at: string;
}

export interface DbEconomyRoleIncome {
  id: string;
  guild_id: string;
  role_id: string;
  amount: number;
  interval_minutes: number;
  created_at: string;
}

export interface DbEconomyRoleIncomeClaim {
  guild_id: string;
  user_id: string;
  role_id: string;
  next_available_at: string;
  last_request_id: string;
  updated_at: string;
}

export interface DbEconomyRoleIncomeRequest {
  guild_id: string;
  user_id: string;
  request_id: string;
  result: {
    status: 'credited' | 'cooldown' | 'no_eligible_roles' | 'verification_unavailable';
    amount_cents: number;
    balance_cents: number | null;
    credited_role_ids: string[];
    blocked_role_ids: string[];
    next_available_at: string | null;
  };
  created_at: string;
}

export type EconomyStreakType = 'daily' | 'weekly' | 'monthly';

export interface DbEconomyStreak {
  guild_id: string;
  user_id: string;
  streak_type: EconomyStreakType;
  current_streak: number;
  longest_streak: number;
  last_claimed_at: string | null;
  next_claim_at: string | null;
  created_at: string;
}

// ── V31 PR #43: Gathering, Crafting, Farming ──────────────

export type LootRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
export type LootSourceType = 'hunt' | 'dig' | 'mine';

export interface DbLootTable {
  id: string;
  guild_id: string;
  source_type: LootSourceType;
  item_name: string;
  emoji: string;
  rarity: LootRarity;
  min_qty: number;
  max_qty: number;
  weight: number;
  tool_tier: number;
  sell_value: number;
  gives_item_id: string | null;
  active: boolean;
  created_at: string;
}

export interface RecipeInput {
  item_name: string;
  qty: number;
}

export interface DbRecipe {
  id: string;
  guild_id: string;
  name: string;
  emoji: string;
  description: string | null;
  inputs: RecipeInput[];
  output_item_id: string | null;
  output_qty: number;
  cooldown_seconds: number;
  category: string;
  is_default: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface DbCrop {
  id: string;
  guild_id: string;
  name: string;
  emoji: string;
  grow_seconds: number;
  wilt_seconds: number;
  sell_price: number;
  seeds_returned: number;
  seed_item_id: string | null;
  category: string;
  sort_order: number;
  is_default: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface DbFarmPlot {
  id: string;
  guild_id: string;
  user_id: string;
  plot_index: number;
  crop_id: string | null;
  planted_at: string | null;
  watered_at: string | null;
  fertilized: boolean;
  harvested: boolean;
  created_at: string;
}

// ── Fishing ───────────────────────────────────────────────

export type FishRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface DbFishSpecies {
  id: string;
  guild_id: string;
  name: string;
  emoji: string;
  rarity: FishRarity;
  min_weight: number;
  max_weight: number;
  base_price: number;
  is_default: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface DbFishCatch {
  id: string;
  guild_id: string;
  user_id: string;
  species_id: string;
  weight: number;
  price_earned: number;
  caught_at: string;
}

// ── Adventures ────────────────────────────────────────────

export type AdventureType = 'dungeon' | 'forest' | 'ocean' | 'space' | 'mountain';
export type AdventureDifficulty = 'easy' | 'normal' | 'hard' | 'legendary';
export type AdventureEndingType = 'success' | 'death' | 'partial';
export type AdventureSessionStatus = 'active' | 'completed' | 'failed' | 'abandoned';

export interface AdventureChoice {
  label: string;
  emoji: string;
  next_scene_index: number | null;
  loot: { item_name: string; qty: number; chance_pct: number }[];
  currency: number;
  damage_pct: number;
  requires_item: string | null;
}

export interface AdventureSceneLoot {
  item_name: string;
  qty: number;
  chance_pct: number;
}

export interface DbAdventure {
  id: string;
  guild_id: string;
  name: string;
  emoji: string;
  description: string | null;
  adventure_type: AdventureType;
  difficulty: AdventureDifficulty;
  min_scenes: number;
  max_scenes: number;
  is_default: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface DbAdventureScene {
  id: string;
  adventure_id: string;
  scene_index: number;
  text: string;
  image_url: string | null;
  choices: AdventureChoice[];
  loot: AdventureSceneLoot[];
  is_ending: boolean;
  ending_type: AdventureEndingType | null;
  created_at: string;
}

export interface DbAdventureSession {
  id: string;
  guild_id: string;
  user_id: string;
  adventure_id: string;
  current_scene_id: string | null;
  status: AdventureSessionStatus;
  loot_collected: { item_name: string; qty: number }[];
  currency_collected: number;
  items_brought: { item_name: string; qty: number }[];
  message_id: string | null;
  channel_id: string | null;
  started_at: string;
  ended_at: string | null;
  // Codex cross-ref fix P5 — bot writes .update({ loot_failed: true })
  loot_failed: boolean;
}

// ── Market ────────────────────────────────────────────────

export type MarketListingStatus = 'active' | 'sold' | 'cancelled' | 'expired';

export interface DbMarketListing {
  id: string;
  guild_id: string;
  seller_id: string;
  item_id: string;
  item_name: string;
  quantity: number;
  remaining: number;
  price_per_unit: number;
  status: MarketListingStatus;
  expires_at: string;
  created_at: string;
}

// ── Trivia ────────────────────────────────────────────────

export type TriviaDifficulty = 'easy' | 'medium' | 'hard';

export interface DbTriviaQuestion {
  id: string;
  guild_id: string;
  category: string;
  difficulty: TriviaDifficulty;
  question: string;
  correct_answer: string;
  wrong_answers: string[];
  created_at: string;
  updated_at: string;
}

// DbTriviaSession / TriviaSessionStatus removed — economy_trivia_sessions was
// created in v31 but DROPped in 20260601000004_v53_dead_table_cleanup.sql and
// never recreated (trivia session state now lives in Valkey). Nothing imported
// the type; no dead usages to fix.

// ── Lottery ───────────────────────────────────────────────

// 'drawing' = claimed, payout pending (intermediate state). The v31 CHECK
// only allowed active/drawn/cancelled; 20260709130000_lottery_stable_winner
// widened it to include 'drawing'.
export type LotteryDrawingStatus = 'active' | 'drawing' | 'drawn' | 'cancelled';

export interface DbLotteryDrawing {
  id: string;
  guild_id: string;
  status: LotteryDrawingStatus;
  jackpot: number;
  winner_user_id: string | null;
  winning_number: number | null;
  drawn_at: string | null;
  created_at: string;
  // 20260709130000 — NULL while payout pending; set with status='drawn'
  winner_paid_at: string | null;
}

export interface DbLotteryTicket {
  id: string;
  drawing_id: string;
  guild_id: string;
  user_id: string;
  ticket_number: number;
  purchased_at: string;
}

// ── Polls ─────────────────────────────────────────────────

export type PollStatus = 'active' | 'closed';

export interface DbPoll {
  id: string;
  guild_id: string;
  channel_id: string;
  message_id: string | null;
  creator_user_id: string;
  title: string;
  description: string | null;
  status: PollStatus;
  allow_multiple: boolean;
  ends_at: string | null;
  created_at: string;
  closed_at: string | null;
}

export interface DbPollOption {
  id: string;
  poll_id: string;
  label: string;
  emoji: string | null;
  sort_order: number;
}

export interface DbPollVote {
  id: string;
  poll_id: string;
  option_id: string;
  user_id: string;
  voted_at: string;
}

// ── Predictions ───────────────────────────────────────────

export type PredictionStatus = 'open' | 'locked' | 'resolved' | 'cancelled';

export interface DbPrediction {
  id: string;
  guild_id: string;
  channel_id: string;
  message_id: string | null;
  creator_user_id: string;
  title: string;
  status: PredictionStatus;
  winning_option_id: string | null;
  total_pool: number;
  created_at: string;
  locked_at: string | null;
  resolved_at: string | null;
}

export interface DbPredictionOption {
  id: string;
  prediction_id: string;
  label: string;
  emoji: string | null;
  sort_order: number;
}

export interface DbPredictionBet {
  id: string;
  prediction_id: string;
  option_id: string;
  guild_id: string;
  user_id: string;
  amount: number;
  placed_at: string;
  payout: number | null;
}

// ── PR #46: Pets, Quests, Achievements, Prestige, Profiles ──

export interface DbPet {
  id: string;
  guild_id: string;
  user_id: string;
  name: string;
  pet_type: string;
  level: number;
  xp: number;
  hunger: number;
  happiness: number;
  energy: number;
  attack: number;
  defense: number;
  speed: number;
  health: number;
  prestige: number;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface DbPetBattle {
  id: string;
  guild_id: string;
  challenger_id: string;
  defender_id: string;
  winner_id: string | null;
  challenger_dmg: number;
  defender_dmg: number;
  reward: number;
  created_at: string;
}

export interface DbQuestTemplate {
  id: string;
  guild_id: string;
  quest_type: string;
  title: string;
  description: string;
  action_type: string;
  target_count: number;
  reward_currency: number;
  reward_xp: number;
  required_module: string | null;
  active: boolean;
  created_at: string;
}

export interface DbQuestProgress {
  id: string;
  guild_id: string;
  user_id: string;
  template_id: string;
  progress: number;
  completed: boolean;
  claimed: boolean;
  assigned_at: string;
  completed_at: string | null;
  // V49 — date portion of assigned_at; unique (guild,user,template,date)
  assigned_date: string;
}

export interface DbAchievementDef {
  id: string;
  guild_id: string;
  name: string;
  description: string;
  badge_emoji: string;
  condition_type: string;
  condition_value: number;
  reward_currency: number;
  reward_xp: number;
  hidden: boolean;
  created_at: string;
}

export interface DbUserAchievement {
  id: string;
  guild_id: string;
  user_id: string;
  achievement_id: string;
  unlocked_at: string;
}

export interface DbPrestige {
  id: string;
  guild_id: string;
  user_id: string;
  prestige_level: number;
  total_resets: number;
  multiplier_pct: number;
  title: string | null;
  last_prestige: string | null;
  created_at: string;
}

export interface DbProfile {
  id: string;
  guild_id: string;
  user_id: string;
  bio: string;
  title: string;
  badge_slots: string[];
  favorite_pet: string | null;
  profile_views: number;
  created_at: string;
  updated_at: string;
}

// ── Heists (economy_heists / economy_heist_participants) ───
// V36 — accessed via the typed client in features/heist/heist-manager.ts.

export type HeistStatus = 'recruiting' | 'in_progress' | 'success' | 'failed' | 'cancelled';

export interface DbHeist {
  id: string;
  guild_id: string;
  initiator_id: string;
  status: HeistStatus;
  target_name: string;
  target_payout: number;
  // ONE-SOURCE-OF-TRUTH refactor (20260710180000): the denormalized
  // participants[] array and the mutable success_chance counter were DROPPED.
  // Crew membership + the live/frozen success chance are DERIVED from the
  // economy_heist_participants ROWS anchored on base_success_chance (the immutable
  // single-member chance = economy_heist_success_base_pct + target difficulty mod).
  base_success_chance: number | null;
  // Resolution state frozen at claim time (20260710060000): the per-person success
  // payout and the decision carried on the intermediate in_progress row so a
  // crash/resume settles the same frozen outcome. NULL while recruiting.
  payout_each: number | null;
  resolution: 'success' | 'failed' | 'cancelled' | null;
  resolved_at: string | null;
  expires_at: string;
  created_at: string;
}

export interface DbHeistParticipant {
  id: string;
  heist_id: string;
  guild_id: string;
  user_id: string;
  role: string;
  payout: number;
  // Per-participant idempotency + freeze markers (20260710060000).
  paid_at: string | null;
  payout_failed: boolean;
  claimed_at: string | null;
  // Frozen entry fee this member actually paid (20260710150000); refunds read this
  // per-row so a config edit after the debit never over/under-refunds.
  entry_fee_paid: number | null;
  joined_at: string;
}

// ── Action Queue DLQ (action_queue_dlq) ───────────────────
// V53 Phase 2 — distinct from dead_letter_queue (DbDeadLetterItem). The
// dashboard action-queue route and the bot's DLQ insert path use the typed
// client. Nullable defaulted columns follow the existing style (non-null).

export interface DbActionQueueDlq {
  id: string;
  guild_id: string;
  action: string;
  // 20260710020000: dead-lettered rows preserve their processing lane
  // (stamped by a BEFORE INSERT trigger) so DLQ listings are self-describing.
  lane: 'commerce' | 'game';
  payload: Record<string, unknown>;
  error_message: string | null;
  retry_count: number;
  max_retries: number;
  original_id: string | null;
  failed_at: string;
  acknowledged: boolean;
  acknowledged_at: string | null;
  retried: boolean;
  retried_at: string | null;
  created_at: string;
}

// ── Health Metrics (health_metrics) ───────────────────────
// V53 Phase 2 — written by diagnostics-service, read by dashboard diagnostics.

export interface DbHealthMetric {
  id: string;
  guild_id: string;
  metric_type: string;
  value_ms: number;
  recorded_at: string;
}

// ── Starboard (starboard_entries) ─────────────────────────
// V17 — accessed via the typed client in features/starboard.

export interface DbStarboardEntry {
  id: string;
  guild_id: string | null;
  source_channel_id: string;
  source_message_id: string;
  starboard_message_id: string | null;
  star_count: number;
  author_id: string;
  created_at: string;
  updated_at: string;
}

// ── Button Roles (button_roles) ───────────────────────────
// V17 — accessed via the typed client in features/reaction-roles/button-roles.

export type ButtonRoleStyle = 'primary' | 'secondary' | 'success' | 'danger';

export interface DbButtonRole {
  id: string;
  guild_id: string | null;
  panel_id: string;
  channel_id: string;
  message_id: string | null;
  label: string;
  emoji: string | null;
  style: ButtonRoleStyle;
  role_id: string;
  sort_order: number;
  exclusive_group: string | null;
  require_role: string | null;
  require_level: number | null;
  active: boolean;
  created_at: string;
  updated_at: string;
}

// ── Sync Reports (sync_reports) ───────────────────────────
// V53 Phase 4 — written by sync/sync-engine via the typed client.

export interface DbSyncReport {
  id: string;
  guild_id: string;
  repaired_count: number;
  attention_count: number;
  total_drift: number;
  details: Record<string, unknown>;
  created_at: string;
}

// ── Level Unlock Configs (level_unlock_configs) ───────────
// V53 Phase 4 — read by services/cross-feature-bridge via the typed client.

export interface DbLevelUnlockConfig {
  guild_id: string;
  feature_key: string;
  required_level: number;
  unlock_message: string | null;
}

// ── Member Feature Unlocks (member_feature_unlocks) ───────
// V53 Phase 4 — upserted by services/cross-feature-bridge via the typed client.

export interface DbMemberFeatureUnlock {
  guild_id: string;
  user_id: string;
  feature_key: string;
  unlocked_at: string;
}

// ── Tutorial (tutorial_configs / tutorial_steps / tutorial_progress) ──
// V53 Phase 3 — accessed via the typed client in features/tutorial and the
// dashboard tutorial route.

export type TutorialTriggerMode = 'first_command' | 'join' | 'disabled';

export interface DbTutorialConfig {
  guild_id: string;
  enabled: boolean;
  auto_trigger: boolean;
  trigger_mode: TutorialTriggerMode;
  updated_at: string;
}

export interface DbTutorialStep {
  id: string;
  guild_id: string;
  step_order: number;
  title: string;
  description: string;
  image_url: string | null;
  built_in_key: string | null;
  enabled: boolean;
  created_at: string;
}

export interface DbTutorialProgress {
  guild_id: string;
  user_id: string;
  current_step: number;
  completed: boolean;
  started_at: string;
  completed_at: string | null;
}

// ── Feature Embed Overrides (feature_embed_overrides) ─────
// V53 Phase 3 — table still exists (20260601000001) but its consumer
// (services/embed-theme) was removed as dead code; the white-label brand kit
// (features/branding) is the supported per-guild embed theming path.

export type FeatureEmbedKey =
  | 'welcome'
  | 'goodbye'
  | 'level_up'
  | 'moderation'
  | 'economy'
  | 'music'
  | 'tickets'
  | 'giveaways'
  | 'achievements';

export interface DbFeatureEmbedOverride {
  guild_id: string;
  feature_key: FeatureEmbedKey;
  color: string | null;
  footer_text: string | null;
  footer_icon_url: string | null;
  thumbnail_url: string | null;
  author_name: string | null;
  updated_at: string;
}

// ── Payment Refunds (payment_refunds) ─────────────────────
// 20260710040000_refund_semantics — one row per PayPal refund/reversal.
// Inserted/selected via the typed client in the dashboard PayPal webhook.

export interface DbPaymentRefund {
  id: string;
  payment_id: string;
  order_id: string | null;
  guild_id: string | null;
  paypal_refund_id: string;
  event_type: string;
  amount_cents: number | null;
  currency: string | null;
  created_at: string;
  paypal_resource_type: 'capture' | 'sale' | null;
  is_terminal_event_witness: boolean;
}

// ── Admin Refund Attempts (commerce_admin_refund_operations) ─
// Append-only PayPal request attempts. Terminal failures remain as durable
// history; request_id is always the same UUID as attempt_id.

export type CommerceAdminRefundAttemptStatus =
  | 'prepared'
  | 'pending'
  | 'provider_completed'
  | 'failed'
  | 'cancelled'
  | 'completed';

export interface DbCommerceAdminRefundOperation {
  attempt_id: string;
  request_id: string;
  order_id: string;
  guild_id: string;
  customer_id: string;
  product_id: string;
  plan_id: string | null;
  actor_id: string;
  paypal_order_id: string | null;
  payment_id: string | null;
  paypal_payment_id: string | null;
  resource_type: 'capture' | null;
  order_amount_cents: number;
  existing_refunded_cents: number;
  refund_amount_cents: number;
  currency: string;
  reason: string;
  provider_required: boolean;
  status: CommerceAdminRefundAttemptStatus;
  provider_status: 'PENDING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | null;
  paypal_refund_id: string | null;
  provider_reported_amount_cents: number | null;
  provider_reported_currency: string | null;
  created_at: string;
  updated_at: string;
  provider_outcome_at: string | null;
  completed_at: string | null;
}
