-- V31 PR #43: Gathering, Crafting, Farming
-- ==============================================
-- New guild_config columns for gathering/crafting/farming settings.
-- New tables: economy_loot_tables, economy_recipes, economy_crops, economy_farm_plots.
--
-- IMPORTANT: This is the FAKE economy. No connection to real-money commerce.

-- ── guild_config additions ──────────────────────────────────

ALTER TABLE guild_config
  ADD COLUMN IF NOT EXISTS economy_gathering_enabled           boolean   NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS economy_gathering_cooldown_seconds  integer   NOT NULL DEFAULT 300,
  ADD COLUMN IF NOT EXISTS economy_crafting_enabled            boolean   NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS economy_crafting_cooldown_seconds   integer   NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS economy_farming_enabled             boolean   NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS economy_farm_grid_size              integer   NOT NULL DEFAULT 9,
  ADD COLUMN IF NOT EXISTS economy_farming_wilt_enabled        boolean   NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS economy_fertilizer_time_reduction_pct integer NOT NULL DEFAULT 50;

-- ── economy_loot_tables ─────────────────────────────────────
-- Defines drop tables for gathering commands (/hunt, /dig, /mine).
-- source_type: 'hunt' | 'dig' | 'mine'
-- tool_tier: minimum tool tier required (0 = bare hands, 1 = basic, 2 = improved, 3 = master)

CREATE TABLE IF NOT EXISTS economy_loot_tables (
  id            uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  guild_id      text    NOT NULL,
  source_type   text    NOT NULL CHECK (source_type IN ('hunt', 'dig', 'mine')),
  item_name     text    NOT NULL,
  emoji         text    NOT NULL DEFAULT '📦',
  rarity        text    NOT NULL DEFAULT 'common' CHECK (rarity IN ('common', 'uncommon', 'rare', 'epic', 'legendary')),
  min_qty       integer NOT NULL DEFAULT 1,
  max_qty       integer NOT NULL DEFAULT 1,
  weight        integer NOT NULL DEFAULT 100,   -- higher weight = more likely
  tool_tier     integer NOT NULL DEFAULT 0,
  sell_value    bigint  NOT NULL DEFAULT 10,     -- base sell price per unit
  gives_item_id uuid    REFERENCES economy_items(id) ON DELETE SET NULL, -- links to shop item if applicable
  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_economy_loot_guild_source
  ON economy_loot_tables (guild_id, source_type) WHERE active = true;

-- ── Default loot entries (applied per-guild on first enable via bot logic) ──
-- Defaults are NOT inserted here — they're generated by the bot when
-- economy_gathering_enabled is first turned on, allowing guild customization.

-- ── economy_recipes ─────────────────────────────────────────
-- Crafting recipes: input materials → output item.
-- inputs: JSONB array of { item_name: string, qty: number } (or item_id references)

CREATE TABLE IF NOT EXISTS economy_recipes (
  id              uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  guild_id        text    NOT NULL,
  name            text    NOT NULL,
  emoji           text    NOT NULL DEFAULT '🔨',
  description     text,
  inputs          jsonb   NOT NULL DEFAULT '[]',    -- [{ "item_name": "Iron Ore", "qty": 3 }, ...]
  output_item_id  uuid    REFERENCES economy_items(id) ON DELETE CASCADE,
  output_qty      integer NOT NULL DEFAULT 1,
  cooldown_seconds integer NOT NULL DEFAULT 0,
  category        text    NOT NULL DEFAULT 'General',
  is_default      boolean NOT NULL DEFAULT false,   -- pre-loaded recipe (not deletable by guild)
  active          boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_economy_recipes_guild
  ON economy_recipes (guild_id) WHERE active = true;

-- ── economy_crops ───────────────────────────────────────────
-- Crop definitions for the farming system.

CREATE TABLE IF NOT EXISTS economy_crops (
  id              uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  guild_id        text    NOT NULL,
  name            text    NOT NULL,
  emoji           text    NOT NULL DEFAULT '🌱',
  grow_seconds    integer NOT NULL DEFAULT 7200,      -- time to mature (default 2hr)
  wilt_seconds    integer NOT NULL DEFAULT 86400,      -- time after maturity before wilting (default 24hr)
  sell_price      bigint  NOT NULL DEFAULT 50,         -- price per unit when sold
  seeds_returned  integer NOT NULL DEFAULT 1,          -- seeds given back on harvest
  seed_item_id    uuid    REFERENCES economy_items(id) ON DELETE SET NULL, -- shop item for seeds
  category        text    NOT NULL DEFAULT 'Vegetable',
  sort_order      integer NOT NULL DEFAULT 0,
  is_default      boolean NOT NULL DEFAULT false,
  active          boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_economy_crops_guild
  ON economy_crops (guild_id) WHERE active = true;

-- ── economy_farm_plots ──────────────────────────────────────
-- Per-user farming grid. Each plot tracks one crop.

CREATE TABLE IF NOT EXISTS economy_farm_plots (
  id              uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  guild_id        text    NOT NULL,
  user_id         text    NOT NULL,
  plot_index      integer NOT NULL CHECK (plot_index >= 0 AND plot_index < 25),
  crop_id         uuid    REFERENCES economy_crops(id) ON DELETE SET NULL,
  planted_at      timestamptz,
  watered_at      timestamptz,
  fertilized      boolean NOT NULL DEFAULT false,
  harvested       boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (guild_id, user_id, plot_index)
);

CREATE INDEX IF NOT EXISTS idx_economy_farm_guild_user
  ON economy_farm_plots (guild_id, user_id);

-- ── RLS ─────────────────────────────────────────────────────

ALTER TABLE economy_loot_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE economy_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE economy_crops ENABLE ROW LEVEL SECURITY;
ALTER TABLE economy_farm_plots ENABLE ROW LEVEL SECURITY;

-- Service role (bot + dashboard) can do everything
CREATE POLICY "service_role_all" ON economy_loot_tables FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON economy_recipes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON economy_crops FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "service_role_all" ON economy_farm_plots FOR ALL USING (true) WITH CHECK (true);
